Repository andes/app, pull requests merged in 2018-09, with the labels that each got.

#674 CITAS - Mostrar código de recupero financiero en el formulario de arancelamiento
  src/app/app.module.ts
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.html
  src/app/services/facturacionAutomatica.service.ts
Labels: prioridad alta

#710 Dar turnos > Calendario
  src/app/components/turnos/dar-turnos/calendario.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Labels: mejora

#773 RUP: Actualización en buscador y corrección de bug de planes/solicitudes
  package-lock.json
  package.json
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/buscador.scss
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/vistaHuds.html
Labels: BugFix, prioridad alta

#760 Log liberar turno
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
Labels: mejora

#785 CITAS > planificar agenda > Precarga select profesionales
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: BugFix

#754 CITAS -> Dar Turnos -> Bloques desordenados
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: BugFix

#803 Citas - Punto Inicio - Dar turno desde solicitud - Fix tipo prestación SMS
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: BugFix

#782 Prestacion no nominalizada
  .angular-cli.json
  package.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/paciente/paciente-detalle.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/interfaces/IPaciente.ts
  src/app/interfaces/ITipoPrestacion.ts
  src/app/modules/mpi/components/demo.component.ts
  src/app/modules/mpi/components/demo.html
  src/app/modules/mpi/components/paciente-buscar.component.ts
  src/app/modules/mpi/components/paciente-buscar.html
  src/app/modules/mpi/components/paciente-buscar.scss
  src/app/modules/mpi/components/paciente-listado.component.ts
  src/app/modules/mpi/components/paciente-listado.html
  src/app/modules/mpi/components/paciente-listado.scss
  src/app/modules/mpi/components/paciente-panel.component.ts
  src/app/modules/mpi/components/paciente-panel.html
  src/app/modules/mpi/components/paciente-panel.scss
  src/app/modules/mpi/interfaces/IPacienteMatch.inteface.ts
  src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
  src/app/modules/mpi/interfaces/PacienteBuscarResultado.inteface.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
  src/app/modules/rup/interfaces/snomed-concept.interface.ts
  src/app/modules/rup/services/elementosRUP.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/services/obraSocial.service.ts
  src/app/services/paciente.service.ts
  src/app/services/profe.service.ts
Labels: nueva funcionalidad

#822 Hot fix no nominalizada
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: BugFix

#824 habilitamos el texto de la evolución
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/vistaCDA.component.ts
  src/app/modules/rup/components/ejecucion/vistaCDA.html
Labels: BugFix

#810 Solucionado el error al mostrar la fecha del análisis de laboratorio
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: bug

#708 CITAS - se agrega control en cambio de fecha de Agendas Dinámicas
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: BugFix
