Repository andes/app, pull requests merged in 2018-10, with the labels that each got.

#777 RUP - Prestación de enfermería
  src/app/app.module.ts
  src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.component.ts
  src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
Labels: nueva funcionalidad

#878 RUP - Filtro sobre prestaciones fuera agenda
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: BugFix

#858 RUP - Cambiar lista de tipos de actividades para no nominalizadas (Y otros)
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: BugFix

#807 MPI -> Se chequea nombre y apellido traido por renaper
  src/app/components/paciente/paciente-detalle.ts
  src/app/services/paciente.service.ts
Labels: mejora

#802 MPI - Empadronamiento paciente - Chequeo textboxes nombre y apellido contra REGEX
  package-lock.json
  package.json
  src/app/components/paciente/paciente-create-update.component.ts
  src/app/components/paciente/paciente-create-update.html
  src/app/services/paciente.service.ts
Labels: mejora

#812 MPI -> Reemplaza nombre/apellido de renaper por SISA en caso de chars inválidos
  src/app/components/paciente/paciente-detalle.html
  src/app/components/paciente/paciente-detalle.ts
Labels: mejora

#891 TOP - fix #886
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: BugFix

#905 mejora en el workflow de la validación
  package-lock.json
  package.json
  src/app/components/paciente/paciente-detalle.ts
Labels: BugFix

#806 CITAS - Control de estado de agenda al verificar solapamiento de profesionales
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
Labels: BugFix

#892 TOP - Se corrige error de prestación en generación de solicitudes desde RUP
  src/app/modules/rup/services/prestaciones.service.ts
Labels: BugFix

#843 CITAS - Revisión de agenda de Odontología
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: BugFix

#902 TOP - Habilita adjuntar documentos en solicitudes de entrada
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/nuevaSolicitud.html
Labels: mejora

#842 MPI-CITAS -> Obra social en SIDEBAR
  src/app/components/paciente/paciente-detalle.html
  src/app/components/paciente/paciente-detalle.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
Labels: mejora
