Repository andes/app, pull requests merged in 2018-07, with the labels that each got.

#580 Fix Mensaje de texto - reasignar un turno
  package-lock.json
  package.json
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
Labels: bug

#610 Issue 581 fecha estimada
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
Labels: mejora

#622 fix extension
  src/app/modules/rup/components/laboratorios/laboratorios.component.ts
Labels: bug

#575 Componente carpetas paciente
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/dashboard/turnos-paciente.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.html
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/punto-inicio/activar-app.component.ts
  src/app/components/turnos/punto-inicio/activar-app.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.scss
  src/app/components/turnos/punto-inicio/paciente-search-turnos.component.ts
  src/app/components/turnos/punto-inicio/paciente-search-turnos.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/components/turnos/punto-inicio/turnos-paciente.scss
  src/app/services/paciente.service.ts
  src/app/services/turnos/turno.service.ts
Labels: mejora

#604 Citas. Agenda Auditada
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
Labels: bug

#648 Carpeta paciente en sobreturnos
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: BugFix, test

#616 fixeo el issue 571 del buscador de rup.
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test

#628 Verificación de asistencia a través del concepto snomed
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: mejora
