Repository andes/app, pull requests merged in 2018-08, with the labels that each got.

#668 Nro. Carpeta paciente en revisión de agenda - Corrección
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: BugFix

#671 CITAS - Punto de inicio - Mejoras en edición de nro de carpeta
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
Labels: BugFix

#673 Actualización formulario arancelamiento
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
Labels: BugFix

#669 Punto de inicio - Bug en cambio de asistencia
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
Labels: BugFix

#675 agregamos lineas perdidas en el merge
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
Labels: BugFix

#677 RUP - Relaciones con niveles anidados
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Labels: prioridad alta

#595 Agendas dinámicas
  package-lock.json
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/dar-turnos/enums.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/interfaces/turnos/IAgenda.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/services/turnos/turno.service.ts
Labels: test

#654 se modifica ruta del puntoInicio de turnos
  src/app/app.component.ts
  src/app/app.routing.ts
  src/app/components/inicio/inicio.html
Labels: BugFix

#623 Puco.v2
  package-lock.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/puco/puco.component.ts
  src/app/components/puco/puco.html
  src/app/components/puco/puco.scss
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/dashboard/turnos-paciente.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/interfaces/IObraSocial.ts
  src/app/interfaces/IProfe.ts
  src/app/modules/rup/components/elementos/ingresoInternacion.html
  src/app/services/obraSocial.service.ts
  src/app/services/periodoPadronesProfe.service.ts
  src/app/services/periodoPadronesPuco.service.ts
  src/app/services/profe.service.ts
  src/app/services/sendmailsugerencias.service.ts
Labels: test

#664 fixed de botones "guardar" y "clonar" que no volvian a aparecer.
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: BugFix

#688 Badge turnos suspendidos Issue#682
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: BugFix

#691 Turnos dobles
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dashboard/turnos-paciente.html
Labels: BugFix

#690 RUP - Filtramos los números de capeta por efector en el punto de inicio
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: BugFix

#699 Búsqueda de profesionales en filtro gestor de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: BugFix

#692 CITAS - Se corrigen inconsistencias en cambios de estado (de agenda) en la Revisión
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
Labels: BugFix

#715 Wizard de Agendas Dinámicas
  .angular-cli.json
  package-lock.json
  package.json
  src/app/assets/wizards/styles.scss
  src/app/classes/wizard.class.ts
  src/app/components/inicio/inicio.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/shared/assets/wizard/agenda.svg
  src/app/shared/assets/wizard/agenda2.svg
  src/app/shared/assets/wizard/checklist.svg
  src/app/shared/assets/wizard/citas-planificarAgendas-darTurnos.png
  src/app/shared/assets/wizard/citas-planificarAgendas-dinamica.png
  src/app/shared/assets/wizard/citas-planificarAgendas-dinamicaCupo.png
  src/app/shared/assets/wizard/medico.svg
  src/app/shared/assets/wizard/pantallas.svg
  src/app/shared/assets/wizard/profesionales.svg
  src/app/shared/assets/wizard/recepcion.svg
  src/app/shared/assets/wizard/styles.scss
Labels: mejora

#721 CITAS - Corrección de márgenes en UI Dar Turnos
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: BugFix

#726 CITAS - Se agrega nota previa del turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: BugFix

#735 Citas > Punto Inicio > carpetas paciente
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
Labels: BugFix

#731 CITAS > Búsquedas recientes en dar turnos
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: bug, mejora

#704 Dar turnos: Modificaciones sidebar de confirmación
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/dar-turnos/dar-turnos.scss
Labels: mejora, test

#738 Punto inicio > Carpetas - Error carpetas duplicadas
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
Labels: BugFix

#739 CITAS - corrección en dar turnos con llave
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: BugFix

#626 Fix crear usuario
  src/app/components/usuario/usuarioCreate.component.ts
  src/app/components/usuario/usuarioCreate.html
Labels: BugFix

#624 Edición de agenda - profesional
  src/app/components/turnos/configuracion/mapa-espacio-fisico/filtros-mapa-espacio-fisico.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/services/turnos/agenda.service.ts
Labels: BugFix, test
