Repository andes/app, pull requests merged in 2019-11, with the labels that each got.

#1457 fix(citas): se resetean parámetros skip y limit en query de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: BugFix

#1486 fix(gestor-usuarios): fix abm perfiles ANGULAR 8
  src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
Labels: bug

#1191 RUP - Crea átomo para registrar una fecha
  src/app/app.module.ts
  src/app/modules/rup/components/elementos/valorFecha.component.ts
  src/app/modules/rup/components/elementos/valorFecha.html
Labels: nueva funcionalidad
