Repository andes/app, pull requests merged in 2019-02, with the labels that each got.

#1024 agrega condicion a boton suspender agenda+ refactor
  package-lock.json
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
Labels: BugFix

#1078 CITAS - Corrige bug en condición de btn suspender
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
Labels: BugFix

#1046 RUP: Visualiza texto del informe del encuentro en trastornos y hallazgos
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
  src/app/modules/rup/services/prestaciones.service.ts
Labels: BugFix

#1076 CITAS/PLEX - layout buscador MPI
  package-lock.json
  package.json
  src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.print.scss
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.html
  src/app/components/turnos/punto-inicio/paciente-search-turnos.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: BugFix

#1057 RUP: Agrega las vacunas al listado de HUDS
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/variables.scss
Labels: nueva funcionalidad

#1080 CITAS - close #1074 #976
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
Labels: BugFix

#1082 CITAS - close #1073
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
Labels: BugFix

#1093 CITAS - Agrega condición en OS del turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: BugFix

#1101 CITAS: Resuelve bug de mostrar el espacio físico si la agenda es suspendida.
  src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts
Labels: BugFix

#1108 agrega horario en el caso de selección de agenda dinámica
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: mejora

#1090 CITAS - Corrige condición al verificar conflictos en la clonación
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Labels: BugFix
