Repository andes/app, pull requests merged in 2019-05, with the labels that each got.

#1180 Corrección de bug en búsqueda de pacientes dentro del componente Sobreturnos
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/core/mpi/components/paciente-cru.component.ts
Labels: BugFix

#1245 RUP - corrección issue #909
  src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
Labels: bug

#1280 V4.4.11
  package.json
  src/app/app.component.ts
  src/app/components/paciente/paciente-search.component.ts
  src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico-vista.component.ts
  src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico-vista.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
Labels: BugFix

#1290 Correcciones varios permisos
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: EC

#1263 RUP - Calculo de la Evaluación de RCV - issue #1222
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.html
  src/app/modules/rup/components/elementos/valorNumerico.html
  src/app/modules/rup/components/formulas/riesgoCardiovascular.service.ts
Labels: BD, BugFix, EV

#1265 PRESTAMOS HC - Imprimir solicitudes
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/prestamosHC/prestamos-hc.component.ts
  src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
Labels: BugFix, EV, mejora

#1308 V4.4.13
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/prestamosHC/prestamos-hc.component.ts
  src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
  src/app/modules/rup/components/elementos/valorNumerico.html
  src/app/modules/rup/components/formulas/riesgoCardiovascular.service.ts
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
  src/app/modules/rup/components/huds/vistaRegistro.html
  src/app/modules/rup/components/huds/vistaRegistro.ts
Labels: BD
