Repository andes/app, pull requests merged in 2019-12, with the labels that each got.

#1367 RUP ~ Procedimientos PDF
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/services/documentos.service.ts
Labels: Aprobado

#1413 HUDS: Corrección en hora de prestación
  src/app/modules/rup/components/huds/vistaPrestacion.html
Labels: Aprobado

#1443 fix(logout): limpiar la cache del browser al cerrar sesion
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/app.routings-guard.class.ts
  src/app/apps/auth/auth.module.ts
  src/app/apps/auth/auth.routing.ts
  src/app/apps/auth/components/login/login.component.ts
  src/app/apps/auth/components/login/login.html
  src/app/apps/auth/components/login/login.scss
  src/app/apps/auth/components/logout/logout.component.ts
  src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
  src/app/apps/auth/components/select-organizacion/select-organizacion.html
  src/app/apps/auth/components/select-organizacion/select-organizacion.scss
  src/environments/environment.dev.ts
Labels: bug

#1401 fix(RUP): Oculta botón Ver Resumen
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado

#1490 RUP: Agrega control en la validación de prestaciones no nominalizadas
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: Aprobado, BugFix

#1464 TOP: Muestra alerta de campo requerido para inputs de prestaciones
  src/app/components/top/solicitudes/nuevaSolicitud.html
Labels: Aprobado

#1498 fix(RUP): Corrige parametro al iniciar prestación pendiente
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: prioridad alta

#1478 TOP: Muestra usuario y fecha de creación en detalle de solicitud
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/detalleSolicitud.html
Labels: Aprobado

#1394 RUP: Odontograma histórico con detalles de piezas
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/especialidad/especialidad-create-update.component.ts
  src/app/components/tipoPrestacion/tipoPrestacion-create-update.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
  src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
  src/app/modules/rup/components/elementos/OdontogramaRefset.html
  src/app/modules/rup/components/elementos/OdontogramaRefset.scss
  src/app/modules/rup/components/huds/vistaDetalleRegistro.html
  src/app/modules/rup/components/huds/vistaDetalleRegistro.scss
  src/app/modules/rup/components/huds/vistaDetalleRegistro.ts
  src/app/modules/rup/components/huds/vistaSolicitudTop.ts
  src/app/modules/rup/components/variables.scss
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
  src/app/modules/rup/services/elementosRUP.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/services/turnos/configPrestacion.service.ts
  src/environments/environment.dev.ts
  tslint.json
Labels: En revisión, nueva funcionalidad

#1430 Internacion - Descarga listado internaciones
  src/app/apps/rup/internacion/components/iniciarInternacion.html
  src/app/apps/rup/internacion/components/listado-internacion.component.ts
  src/app/apps/rup/internacion/components/listado-internacion.html
  src/app/apps/rup/internacion/components/mapa-de-camas.component.ts
  src/app/services/documentos.service.ts
Labels: En revisión

#1448 feat(oferta-prestacional): ABM de ofertas prestacionales
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/organizacion/organizacion-prestaciones.component.ts
  src/app/components/organizacion/organizacion-prestaciones.html
  src/app/components/organizacion/organizacion.component.ts
  src/app/components/organizacion/organizacion.html
  src/app/interfaces/IOrganizacion.ts
  src/app/services/organizacion.service.ts
Labels: En revisión, request changes

#1511 fix(RUP): Control para solicitudes con pedido de auditoria
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado, BugFix

#1514 fix(Internacion): Control para elementoRup en null
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Labels: BugFix

#1461 HUDS: cambia bagdes de origen de solicitud
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: request changes
