Repository andes/app, pull requests merged in 2019-04, with the labels that each got.

#1170 CITAS: Se reemplaza la información estadística de agendas por información útil al usuario.
  src/app/components/turnos/dashboard/estadisticas-agendas.component.ts
  src/app/components/turnos/dashboard/estadisticas-agendas.html
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
Labels: Urgente

#1186 CITAS: Verifica que el efector tenga habilitación para cupo mobile
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: mejora

#1185 CITAS: Corrección de Issues relacionados con los espacios físicos
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: BugFix

#1196 RUP - Quita la búsqueda de valores en huds para IMC
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/elementos/indiceDeMasaCorporal.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: mejora

#1104 Citas: Resolución de Issue709
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: BugFix

#1205 CITAS: Quita el acceso a la obra social para los sobre turnos
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
Labels: Urgente

#1209 TM Profesional: agrega control para nuevo profesional
  src/app/components/profesional/profesional-create-update.component.ts
Labels: BugFix

#1214 Organización: Arregla el problema de botones flotantes
  src/app/components/organizacion/organizacion-create-update.html
Labels: bug

#1212 RUP: Se resuelve problema de actividades comunidad al subir archivo.
  src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
Labels: BugFix
