Repository andes/app, pull requests merged in 2019-07, with the labels that each got.

#1352 feat(arancelamiento): agrega firma profesional en impresion
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/services/profesional.service.ts
Labels: EV

#1368 Agrega error handler en liberación de turno
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
Labels: Aprobado

#1326 CITAS - Calendario en clonación de agendas (Issue #1194)
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Labels: Aprobado

#1342 Navigation refactor para MPI 2
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/core/mpi/components/bebe-cru.component.ts
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/core/mpi/components/extranjero-nn-cru.component.ts
  src/app/core/mpi/components/mpi-botones-registro.component.ts
  src/app/core/mpi/components/paciente-cru.component.ts
  src/app/services/previous-url.service.ts
Labels: Aprobado

#1344 Verifica la existencia de telefono antes de llamar al servicio de SMS
  src/app/components/top/reglas/reglas.component.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
  src/app/components/turnos/gestor-agendas/turnos.component.ts
Labels: Aprobado

#1372 MPI - buscador de pacientes falla cuando el scan da match alto con temporal
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/modules/mpi/components/paciente-buscar.component.ts
Labels: BugFix
