Repository andes/app, pull requests merged in 2020-02, with the labels that each got.

#1539 TOP: refactorizar pantalla de solicitudes con plex-layout
  src/app/components/top/solicitudes/anularSolicitud.html
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/nuevaSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: changes done

#1505 CITAS: Se agrega la organizacion al no asignar turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: changes done

#1480 MPI - Dirección legal en pacientes
  src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
  src/app/core/mpi/components/paciente-cru.component.ts
  src/app/core/mpi/components/paciente-cru.html
Labels: En revisión

#1531 TOP: Mejora la búsqueda de solicitudes
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/solicitudes/solicitudes.scss
Labels: En revisión

#1494 RUP: Recarga agenda seleccionada
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: En revisión

#1580 RUP: se modifican llamados a la api en la recarga del punto de inicio
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: Urgente
