Repository andes/app, pull requests merged in 2020-05, with the labels that each got.

#1634 TOP: corrige filtro estados x defecto
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: BugFix, Urgente

#1660 fix(solicitudes): formatea fechas default a Date
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: BugFix, Urgente

#1612 TOP: arregla filtro de turno dado con tipo de prestación
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: BugFix

#1585 TOP: Historial de solicitudes
  src/app/app.module.ts
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/historialSolicitud.component.ts
  src/app/components/top/solicitudes/historialSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/modules/rup/components/huds/vistaSolicitudTop.html
Labels: En revisión

#1523 CITAS: Visualizacion de otros espacios fisicos
  src/app/app.module.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/interfaces/turnos/IAgenda.ts
  src/app/interfaces/turnos/IInstitucion.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/pipes/espacioFisico.pipe.ts
  src/app/services/turnos/institucion.service.ts
Labels: En revisión

#1540 CITAS: Al suspender una agenda en el gestor no se actualiza el estado
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: Aprobado

#1570 TOP: Arregla llamados repetidos a la API
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: Aprobado

#1652 RUP: Arregla cancelar desvinculación de pieza
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: BugFix

#1574 MISC: Visualización de novedades y armado dinámico de cajas
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/inicio/inicio.component.ts
  src/app/components/inicio/inicio.html
  src/app/components/inicio/inicio.scss
  src/app/components/novedades/common-novedades.service.ts
  src/app/components/novedades/header-novedades/header-novedades.component.html
  src/app/components/novedades/header-novedades/header-novedades.component.ts
  src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.html
  src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.ts
  src/app/components/novedades/lista-novedades/lista-novedades.component.html
  src/app/components/novedades/lista-novedades/lista-novedades.component.ts
  src/app/components/novedades/novedades.component.html
  src/app/components/novedades/novedades.component.ts
  src/app/components/novedades/novedades.scss
  src/app/interfaces/novedades/IModulo.interface.ts
  src/app/interfaces/novedades/INovedad.interface.ts
  src/app/services/novedades/modulos.service.ts
  src/app/services/novedades/novedades.service.ts
  src/styles.scss
Labels: En revisión

#1542 feat(Odontograma): números para cantidad de registros en piezas/caras dentales
  package-lock.json
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
  src/app/modules/rup/components/elementos/OdontogramaRefset.html
Labels: mejora UI/UX
