Repository andes/app, pull requests merged in 2020-12, with the labels that each got.

#2066 DASHBOARD: Error al filtrar por una prestacion
  src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
  src/app/modules/estadisticas/components/rup/rup-pacientes.html
Labels: test ok

#2062 MPI - Nuevo servicio para carpeta de paciente
  src/app/app.module.ts
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/prestamosHC/historial/historial-hc.component.ts
  src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/core/mpi/services/carpeta-paciente.service.ts
  src/app/core/mpi/services/paciente.service.ts
Labels: test ok

#2070 refactor(HUDS):registros, agregar links a otros registros y a prestacion
  src/app/modules/rup/components/core/_rup.scss
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
Labels: Aprobado, test ok

#2032 CIT: refactor arancelamiento
  src/app/app.module.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.html
  src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.scss
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/services/documentos.service.ts
  src/app/services/facturacionAutomatica.service.ts
  src/app/services/profesional.service.ts
Labels: test ok

#2073 MPI - permite dni con 5 digitos
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2069 TM - Modifica response en validación por FA
  src/app/components/profesional/profesional-create-update.component.ts
Labels: test ok

#2053 MPI - Visualizacion datos reporte de error
  src/app/modules/auditoria/auditoria.module.ts
  src/app/modules/auditoria/component/auditoria-listado.component.ts
  src/app/modules/auditoria/component/auditoria-listado.html
  src/app/modules/auditoria/component/auditoria.component.ts
  src/app/modules/auditoria/component/auditoria.html
  src/app/modules/auditoria/component/modal-correccion-paciente.component.ts
  src/app/modules/auditoria/component/modal-correccion-paciente.html
  src/app/modules/auditoria/component/reporte-errores.component.ts
  src/app/modules/auditoria/component/reporte-errores.html
Labels: test ok

#2067 MPI - Corrige guardado de relación sin parentesco (editando)
  src/app/core/mpi/components/relaciones-pacientes.component.ts
  src/app/core/mpi/components/relaciones-pacientes.html
Labels: test ok

#2068 COM: refactor de archivos con andesDrive y shared-galeria-archivos
  projects/shared/src/lib/shared.module.ts
  src/app/app.module.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/actualizar-estado.html
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/historial-derivacion.component.ts
  src/app/modules/com/components/historial-derivacion.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
  src/app/shared/components/upload-file.component.ts
Labels: test fail

#2076 chore(plex): actualiza a v7.9.0
  package-lock.json
  package.json
Labels: mejora UI/UX, plex, test ok

#2081 INTERNACION - Controla que se haya generado el censo para poder descargarlo
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Labels: Aprobado, test fail

#2079 fix(CITAS): poder seleccionar prepaga cuando el paciente no tiene obra social
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
Labels: test fail

#2083 MPI - Corrección de datos de un paciente en modal
  src/app/modules/auditoria/component/auditoria.html
  src/app/modules/auditoria/component/modal-correccion-paciente.component.ts
  src/app/modules/auditoria/component/modal-correccion-paciente.html
Labels: test ok

#2078 CIT: registrar motivo liberación turno
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/utils/enumerados.ts
Labels: test ok

#2072 BI-QUERIES: Campo obligatorio/no obligatorio "organización" en bi queries
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: test ok

#2055 TURNOS-PRESTACIONES: Descarga de prestaciones desde el buscador de turnos y prestaciones
  src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
  src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.html
  src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.ts
  src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.html
  src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
  src/app/modules/visualizacion-informacion/services/export-huds.service.ts
  src/app/modules/visualizacion-informacion/visualizacion-informacion.module.ts
Labels: Aprobado, test ok

#2082 feat(CIT): mostrar espacio fisico dacion turno
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: test fail

#2084 COM: borrar archivos del drive al eliminar de la galería
  src/app/app.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/services/drive.service.ts
Labels: test ok

#2056 COM: Ordenar listado por columnas
  package-lock.json
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
  src/app/modules/com/components/punto-inicio.scss
  src/app/modules/com/services/punto-inicio.service.ts
Labels: test ok

#2077 feat(HUDS): registros, mostrar adjuntos si esta relacionado
  src/app/modules/rup/components/elementos/adjuntarDocumento.html
  src/app/modules/rup/components/huds/vistaProcedimiento.html
  src/app/modules/rup/components/huds/vistaProcedimiento.ts
  src/app/modules/rup/components/huds/vistaRegistro.html
  src/app/modules/rup/components/huds/vistaRegistro.ts
Labels: Aprobado, test ok

#2087 INTERNACION - Agrega control en los registros si la unidad organizativa es null
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
Labels: test ok

#2086 Quita dependencia rxjs-compat
  package-lock.json
  package.json
  projects/auth/package.json
  projects/auth/src/lib/auth.service.ts
  projects/shared/package.json
  projects/shared/src/lib/server/server.service.ts
  src/app/apps/gestor-usuarios/services/perfiles.http.ts
  src/app/apps/gestor-usuarios/services/permisos.service.ts
  src/app/apps/gestor-usuarios/services/usuarios.http.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
  src/app/apps/turnero/services/turnero.service.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/modules/rup/services/huds.service.ts
  src/app/modules/rup/services/plantillas.service.ts
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
  src/app/services/drive.service.ts
  src/app/services/query.service.ts
  src/app/services/siisa.service.ts
  src/app/services/websocket.service.ts
Labels: test ok

#2080 feat(TOP): mostrar cantidad auditoria
  src/app/components/top/pipes/auditorias-solicitud.pipe.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
Labels: test ok

#2090 GDU: feedback al usuario cuando no encuentra resultados
  src/app/apps/gestor-usuarios/views/usuarios-list.view.html
  src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
Labels: test ok

#2091 TURNOS-PRESTACIONES: Agregar virtual scroll y filtro ambito
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.scss
Labels: Aprobado, test ok

#2094 feat(RUP): Agregar registro de vacuna covid
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/vacunas.component.ts
  src/app/modules/rup/components/elementos/vacunas.html
  src/app/modules/rup/elementos-rup.module.ts
  src/app/services/vacunas.service.ts
Labels: test ok

#2092 INTERNACION - Controla manualmente la fecha de egreso ingresada
  package-lock.json
  package.json
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok

#2089 TOP: subir archivos a andesDrive
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/components/top/solicitudes/formNuevaSolicitud.html
Labels: test ok

#1848 RUP: Enviar archivos ajuntos por mail
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
  src/app/modules/rup/components/ejecucion/modal-seleccion-email.component.ts
  src/app/modules/rup/components/ejecucion/modal-seleccion-email.html
Labels: Aprobado, test ok

#2085 MPI: Se obtiene el número de trámite de dni del paciente
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok
