Repository andes/app, pull requests merged in 2020-01, with the labels that each got.

#1479 RUP: Muestra frecuentes por defecto
  src/app/modules/rup/components/ejecucion/buscador.component.ts
Labels: En revisión

#1459 TOP: Incluye prioridad de solicitud
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: En revisión

#1500 fix(rup): matiene formato HTML es ObservacionesComponent
  src/app/modules/rup/components/elementos/informe.component.ts
  src/app/modules/rup/components/elementos/informe.html
  src/app/modules/rup/components/elementos/observaciones.component.ts
  src/app/modules/rup/components/elementos/observaciones.html
Labels: Aprobado

#1428 TM - Editar profesionales no matriculados
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/profesional/profesional-create-update.component.ts
  src/app/components/profesional/profesional-create-update.html
  src/app/components/profesional/profesional.component.ts
  src/app/components/profesional/profesional.html
  src/app/interfaces/ISiisa.ts
  src/app/services/profesional.service.ts
  src/app/services/siisa.service.ts
Labels: En revisión

#1483 CITAS: agrega paciente a agenda dinámica
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: request changes

#1444 Prestamos HC: incorpora unsubscribe en request
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/prestamosHC/prestamos-hc.component.ts
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
Labels: En revisión

#1463 TOP: limpia opciones de Selects
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.html
Labels: En revisión

#1497 feat(gestor-usuario): add visibility attribute
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
Labels: En revisión

#1533 TOP: incluye observaciones en aceptación de solicitud
  src/app/components/top/solicitudes/anularSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/modules/rup/components/huds/vistaSolicitudTop.html
  src/app/modules/rup/components/huds/vistaSolicitudTop.ts
Labels: En revisión

#1515 TURNERO: sumado tipo a la configuración de pantallas
  src/app/app.routing.ts
  src/app/apps/turnero/services/pantalla.service.ts
  src/app/apps/turnero/turnero.routing.ts
  src/app/apps/turnero/views/pantalla-detalle.component.ts
  src/app/apps/turnero/views/pantalla-detalle.html
  src/app/apps/turnero/views/pantallas.component.ts
  src/app/apps/turnero/views/pantallas.html
  src/app/apps/turnero/views/pantallas.scss
Labels: Aprobado

#1473 HUDS - Privacidad
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/app.routings-guard.class.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
  src/app/modules/rup/components/huds/vista-accesos-huds.component.ts
  src/app/modules/rup/components/huds/vista-accesos-huds.html
  src/app/modules/rup/components/huds/vista-accesos-huds.scss
  src/app/modules/rup/services/huds.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/modules/rup/services/resumenPaciente-dinamico.service.ts
Labels: En revisión

#1549 fix(RUP): Agregar la organización en la ejecución de las prestaciones fuera de agenda
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
Labels: BugFix

#1548 fix(plex-item) input sin uso rompe la compilación
  package-lock.json
  package.json
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
Labels: BugFix, En revisión, plex

#1456 CITAS: visualizar la cantidad de pacientes simultáneos por turno o con citación por segmento
  package-lock.json
  package.json
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: changes done
