Repository andes/app, pull requests merged in 2020-10, with the labels that each got.

#1917 MPI - Nuevo componente paciente-busqueda
  src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
  src/app/components/auditoria/auditoria.html
  src/app/components/auditoria/vincular-pacientes.html
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/top/solicitudes/busquedaPaciente.html
  src/app/components/top/solicitudes/nuevaSolicitud.html
  src/app/components/turnos/autocitar/dinamica.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/core/mpi/components/busqueda-mpi.component.ts
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/datos-basicos.html
  src/app/core/mpi/components/datos-basicos.scss
  src/app/core/mpi/components/relaciones-pacientes.html
  src/app/core/mpi/services/paciente-buscar.service.ts
  src/app/modules/auditoria/component/vincular-pacientes.html
  src/app/modules/mpi/components/paciente-buscar.component.ts
  src/app/modules/mpi/components/paciente-buscar.html
  src/app/modules/mpi/components/paciente-busqueda.component.ts
  src/app/modules/mpi/components/paciente-busqueda.html
  src/app/modules/mpi/components/paciente-listado.component.ts
  src/app/modules/mpi/components/paciente-listado.html
  src/app/modules/mpi/mpi-lib.module.ts
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.scss
  src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
  src/app/modules/rup/components/internacion/puntoInicio-internacion.html
Labels: test ok

#1926 COM: nuevo módulo centro operativo médico
  projects/shared/src/lib/components/popover-audit/popover-audit.component.ts
  src/app/app.routing.ts
  src/app/interfaces/IOrganizacion.ts
  src/app/modules/com/com.module.ts
  src/app/modules/com/com.routing.ts
  src/app/modules/com/components/adjuntos.scss
  src/app/modules/com/components/busqueda-paciente.component.ts
  src/app/modules/com/components/busqueda-paciente.html
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/historial-derivacion.component.ts
  src/app/modules/com/components/historial-derivacion.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
  src/app/modules/com/interfaces/IDerivacion.interface.ts
  src/app/modules/com/interfaces/IDerivacionHistorial.interface.ts
  src/app/services/com/adjuntos.service.ts
  src/app/services/com/derivaciones.service.ts
  src/app/services/com/reglasDerivaciones.service.ts
Labels: test ok

#1895 RUP: posibilidad de registrar conceptos repetidos en una prestación
  src/app/modules/rup/interfaces/elementoRUP.interface.ts
  src/app/modules/rup/services/ejecucion.service.ts
Labels: Aprobado, test ok

#1883 refactor(RUP): molecula-base incorpora funcionalidad de ultimo regist…
  src/app/modules/rup/components/core/rup.html
  src/app/modules/rup/components/elementos/moleculaBase.component.ts
Labels: Aprobado, test ok

#1934 INTERNACION - Agrega el nombre completo de los sectores.
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
  src/app/services/organizacion.service.ts
Labels: test ok

#1899 RUP: filtros por semanticTag a SelectSnomedComponent
  src/app/modules/rup/components/elementos/rupers/select-snomed.component.ts
Labels: test ok

#1936 TM: configurar aceptaDerivacion en organizaciones
  src/app/components/organizacion/organizacion-create-update.html
Labels: test fail

#1920 Bi-queries: Módulo para englobar todo tipo de salida de informacion
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: test ok

#1937 COM: control de permisos
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/punto-inicio.component.ts
Labels: test ok

#1940 COM: permitir sumar notas/adjuntos a estado actual
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/actualizar-estado.html
  src/app/modules/com/components/historial-derivacion.component.ts
  src/app/modules/com/components/historial-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
Labels: test ok

#1938 fix(RUP):control de requerido en atomo adjuntar documento
  src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.html
Labels: Aprobado, test ok

#1923 Performance
  projects/auth/src/lib/auth.service.ts
  projects/shared/src/lib/decorator/cache.ts
  projects/shared/src/lib/operators/cache-storage.ts
  projects/shared/src/lib/operators/index.ts
  projects/shared/src/lib/operators/not-null.ts
  projects/shared/src/lib/server/server.service.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routings-guard.class.ts
  src/app/apps/auth/components/accept-disclaimer/modal-disclaimer.component.ts
  src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/services/elementosRUP.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/services/barrio.service.ts
  src/app/services/conceptos-turneables.service.ts
  src/app/services/disclaimer.service.ts
  src/app/services/localidad.service.ts
  src/app/services/obraSocial.service.ts
  src/app/services/pais.service.ts
  src/app/services/parentesco.service.ts
  src/app/services/provincia.service.ts
Labels: test ok

#1944 chore(plex): v7.2.0
  package-lock.json
  package.json
Labels: Aprobado, test ok

#1935 feat(gestor-agendas): mejora interactividad al editar agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
Labels: mejora UI/UX, test ok

#1855 CITAS: Lazy load de historial de turno + limpieza de código
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
Labels: test ok

#1947 fix(COM): Se modifican los filtros que habían quedado con los enumerados anteriores
  src/app/modules/com/components/punto-inicio.component.ts
Labels: BugFix

#1943 TOP: refactor visual en listado de solicitudes
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/solicitudes/solicitudes.scss
Labels: test ok

#1924 Internacion sala espera
  src/app/apps/rup/mapa-camas/interfaces/ISalaComun.ts
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.html
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.service.ts
Labels: test ok

#1914 GDU: permisos unidades organizativas de internacion
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.ts
  src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
  src/app/services/organizacion.service.ts
Labels: Aprobado, test ok

#1942 refactor(rup): crear solicitudes en background
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test ok

#1824 TOP: refactor listado de solicitudes
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/busquedaPaciente.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/historialSolicitud.component.ts
  src/app/components/top/solicitudes/historialSolicitud.html
Labels: En revisión, test ok

#1957 fix(RUP): al continuar registro, la solicitud pierde el formato
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
Labels: test ok

#1952 perf(huds): quita sort innecesario
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test ok

#1932 CITAS - Habilita turnos de gestion en agendas del dia
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/calendario.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/interfaces/turnos/IBloque.ts
Labels: test ok

#1959 COM: se suma fecha de creación/actualización a listado de derivaciones
  src/app/modules/com/components/punto-inicio.html
Labels: test ok

#1953 COM: limpiar sidebars al cambiar de derivación
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
Labels: test ok

#1962 perf(top): evita calcular estado todo el tiempo
  src/app/components/top/pipes/estado-solicitud.pipe.ts
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
  src/app/modules/rup/interfaces/prestacion.interface.ts
Labels: test ok

#1955 COM: permitir al com cancelar sus derivaciones solicitadas
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
Labels: test ok

#1949 INTERNACION - Agregar o sacar columnas adicionales de la tabla
  src/app/apps/rup/mapa-camas/interfaces/mapa-camas.internface.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: Aprobado, test ok

#1945 INTERNACION - Deshacer internacion si tiene ingreso solamente
  src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: Aprobado, test ok

#1963 INTERNACION - Agrega sector completo al abm de sala comun
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.html
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
Labels: Aprobado, test ok

#1974 fix(mapa-camas): handle null al borrar sector
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
Labels: test ok

#1948 GDU: fix ExpressionChangedAfterItHasBeenCheckedError perfiles
  src/app/apps/gestor-usuarios/services/perfiles.http.ts
  src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
Labels: test ok

#1967 COM: uso de componente paciente-busqueda en com
  src/app/modules/com/components/busqueda-paciente.html
Labels: test ok

#1975 COM: marcar derivación seleccionada en plex-list
  src/app/modules/com/components/punto-inicio.html
Labels: test ok

#1954 MPI - fix crear prestacion autocitación; elimina componente agregarPaciente
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
Labels: test ok

#1746 INTERNACION - Agrega componente de integridad de camas
  src/app/apps/rup/mapa-camas/interfaces/IInconsistencia.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
  src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.html
  src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.ts
  src/app/apps/rup/mapa-camas/views/integridad/filtros-inconsistencia/filtros-inconsistencias.component.html
  src/app/apps/rup/mapa-camas/views/integridad/filtros-inconsistencia/filtros-inconsistencias.component.ts
  src/app/apps/rup/mapa-camas/views/integridad/integridad-camas.component.html
  src/app/apps/rup/mapa-camas/views/integridad/integridad-camas.component.ts
  src/app/apps/rup/mapa-camas/views/integridad/integridad.service.ts
  src/app/apps/rup/mapa-camas/views/integridad/item-inconsistencia/item-inconsistencia.component.html
  src/app/apps/rup/mapa-camas/views/integridad/item-inconsistencia/item-inconsistencia.component.ts
Labels: has conflicts, revisar, test ok

#1880 INTERNACION - Controla la fecha de egreso con el historial de la cama
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: Aprobado, test ok

#1901 Punto inicio ANDES
  package-lock.json
  src/app/app.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/components/inicio/inicio.component.ts
  src/app/components/inicio/inicio.html
  src/app/components/inicio/inicio.scss
  src/app/components/turnos/punto-inicio/paciente-search-turnos.html
  src/app/modules/rup/components/core/_rup.scss
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/internacion/puntoInicio-internacion.html
  src/app/styles/acronimo.svg.ts
  src/app/styles/logo.svg.ts
  src/styles.scss
Labels: En revisión, test ok

#1969 refactor(carpeta-paciente): incorpora componentes plex
  src/app/components/carpeta-paciente/carpeta-paciente.html
Labels: test ok

#1928 RUP - Invalidar inicio de prestación
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/interfaces/prestacionGetParams.interface.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test ok

#1964 CORE: angular handler error
  projects/shared/src/lib/server/error-handler.service.ts
  projects/shared/src/public-api.ts
  src/app/app.module.ts
Labels: test ok

#1979 fix(menu): se evitan items repetidos
  src/app/app.component.ts
Labels: test ok

#1980 Revision de agenda dinámicas
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
Labels: test ok

#1946 MPI - modifica formato de foto de pacientes
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/components/relaciones-pacientes.component.ts
  src/app/core/mpi/components/relaciones-pacientes.html
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-panel.component.ts
  src/app/modules/mpi/components/paciente-panel.html
  src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
Labels: test ok

#1992 TOP: arreglo de dropdown en solicitudes asignada
  src/app/components/top/pipes/estado-solicitud.pipe.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: test ok

#1961 RUP: elimina la font rup
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
  src/app/modules/rup/assets/font.css
  src/app/modules/rup/assets/fonts/rup.eot
  src/app/modules/rup/assets/fonts/rup.svg
  src/app/modules/rup/assets/fonts/rup.ttf
  src/app/modules/rup/assets/fonts/rup.woff
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.html
  src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.html
  src/app/modules/rup/components/huds/vistaCDA.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaProcedimiento.html
  src/app/modules/rup/components/huds/vistaRegistro.html
  src/app/modules/rup/components/huds/vistaSolicitudTop.html
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/pipes/semantic-class.pipes.ts
  src/app/modules/rup/pipes/semantic-icon.pipes.ts
  src/app/modules/rup/rup-lib.module.ts
  src/app/modules/rup/services/elementosRUP.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/styles.scss
Labels: script, test ok

#1988 fix(mpi): setea fecha de fallecimiento
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#1991 Visualización de información: Eliminar "cajas" al ingresar a Visualización de Información y Dasboard
  src/app/modules/estadisticas/components/home.component.ts
  src/app/modules/estadisticas/components/home.html
  src/app/modules/estadisticas/estadisticas.routing.ts
  src/app/modules/visualizacion-informacion/components/visualizacion-informacion.component.html
  src/app/modules/visualizacion-informacion/components/visualizacion-informacion.component.ts
  src/app/modules/visualizacion-informacion/components/visualizacion-informacion.scss
  src/app/modules/visualizacion-informacion/visualizacion-informacion.routing.ts
Labels: test ok

#1986 COM: seleccionar por defecto el profesional logueado
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
Labels: test ok

#1968 TOP: uso de componente mpi paciente-busqueda
  src/app/components/top/solicitudes/busquedaPaciente.html
Labels: test ok

#2002 fix(RUP):punto-inicio,error al crear prestaciones fuera de agenda(loa…
  src/app/modules/mpi/components/paciente-detalle.component.ts
Labels: Aprobado, test ok

#1993 MPI - Direccion y telefono por defecto en sidebar detalles
  src/app/core/mpi/components/busqueda-mpi.component.ts
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/modules/mpi/components/paciente-detalle.component.ts
Labels: test ok

#1996 CIT: incluye createdBy en detalle de agenda
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: test ok

#1990 TOP: guarda organización al iniciar prestación
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: test ok

#1994 chore(plex): v7.3.0
  package-lock.json
  package.json
Labels: test ok

#2005 INTERNACION - Corrige accion saltar al presente que quitaba la fecha
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
Labels: Aprobado, test ok

#1999 fix(RUP):Punto-Inicio,No es posible continuar registro de Prestación …
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#1982 fix(menu): comprueba módulos con permisos múltiples
  src/app/app.component.ts
Labels: test ok

#1965 MPI - Pacientes agregados a prestacion no nominalizada
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.scss
Labels: test ok

#1989 TOP: fix en eliminar adjunto
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.html
Labels: test ok

#1985 fix(novedades): se separa array de novedades
  src/app/app.component.ts
  src/app/components/inicio/inicio.component.ts
  src/app/components/inicio/inicio.html
Labels: test ok

#1977 INTERNACION - Aplica plex-wrapper en form egreso e ingreso de pacientes
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
Labels: Aprobado, test ok

#2006 Turnos-prestaciones: Fix conceptId
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/modules/estadisticas/components/home.component.ts
  src/app/modules/estadisticas/components/home.html
  src/app/modules/estadisticas/components/home.scss
  src/app/modules/estadisticas/estadistica.module.ts
Labels: Aprobado, test ok

#2009 INTERNACION - Anula prestacion al deshacer internacion
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: changes done, test ok

#2011 Dashboard: fix permisos actualizados
  src/app/modules/estadisticas/components/citas/filtros.component.ts
Labels: test ok

#2013 chore(plex): v7.3.1
  package-lock.json
  package.json
Labels: test ok
