Repository andes/app, pull requests merged in 2020-09, with the labels that each got.

#1856 elementos-rup: elimina atomos y moleculas que no deberían existir
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/tipoPrestacion/tipoPrestacion-create-update.component.ts
  src/app/components/tipoPrestacion/tipoPrestacion-create-update.html
  src/app/components/tipoPrestacion/tipoPrestacion.component.ts
  src/app/components/tipoPrestacion/tipoPrestacion.html
  src/app/components/top/top.module.ts
  src/app/components/turnos/citas.module.ts
  src/app/directives/directives.module.ts
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
  src/app/modules/rup/components/ejecucion/resumen-paciente/chart.component.ts
  src/app/modules/rup/components/ejecucion/resumen-paciente/chart.html
  src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoE2Y3A.component.ts
  src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoE3Y6A.component.ts
  src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoM2A.component.ts
  src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoM2A.html
  src/app/modules/rup/components/elementos/circunferenciaCintura.component.ts
  src/app/modules/rup/components/elementos/circunferenciaCintura.html
  src/app/modules/rup/components/elementos/consultaDeNinoSanoE2Y3A.component.ts
  src/app/modules/rup/components/elementos/consultaDeNinoSanoE3Y6A.component.ts
  src/app/modules/rup/components/elementos/consultaDeNinoSanoM2A.component.ts
  src/app/modules/rup/components/elementos/desarrolloPsicomotorNormal.html
  src/app/modules/rup/components/elementos/desarrolloPsicomotorTrastorno.html
  src/app/modules/rup/components/elementos/filtradoGlomerular.component.ts
  src/app/modules/rup/components/elementos/filtradoGlomerular.html
  src/app/modules/rup/components/elementos/hipertensionArterial.component.ts
  src/app/modules/rup/components/elementos/lugarDeNacimiento.component.ts
  src/app/modules/rup/components/elementos/lugarDeNacimiento.html
  src/app/modules/rup/components/elementos/obesidad.component.ts
  src/app/modules/rup/components/elementos/odontologiaDefault.component.ts
  src/app/modules/rup/components/elementos/odontologiaDefault.html
  src/app/modules/rup/components/elementos/otoemisionAcusticaDeOidoDerecho.component.ts
  src/app/modules/rup/components/elementos/otoemisionAcusticaDeOidoIzquierdo.component.ts
  src/app/modules/rup/components/elementos/otoemisionOidoDerecho.html
  src/app/modules/rup/components/elementos/otoemisionOidoIzquierdo.html
  src/app/modules/rup/components/elementos/percentiloDeMasaCorporal.component.ts
  src/app/modules/rup/components/elementos/percentiloDeMasaCorporal.html
  src/app/modules/rup/components/elementos/percentiloDeTensionArterial.component.ts
  src/app/modules/rup/components/elementos/percentiloDeTensionArterial.html
  src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.component.ts
  src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.html
  src/app/modules/rup/components/elementos/percentiloPeso.component.ts
  src/app/modules/rup/components/elementos/percentiloPeso.html
  src/app/modules/rup/components/elementos/percentiloTalla.component.ts
  src/app/modules/rup/components/elementos/percentiloTalla.html
  src/app/modules/rup/components/elementos/perimetroCefalico.component.ts
  src/app/modules/rup/components/elementos/perimetroCefalico.html
  src/app/modules/rup/components/elementos/signosVitales.component.ts
  src/app/modules/rup/components/elementos/signosVitales.html
  src/app/modules/rup/components/elementos/tensionArterial.component.ts
  src/app/modules/rup/components/elementos/tensionArterialPediatrica.component.ts
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/rup-lib.module.ts
  src/app/modules/rup/rup.module.ts
  src/app/modules/rup/rup.routing.ts
Labels: Aprobado, script

#1828 elementos-rup: requeridos filtros por sexo
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/core/rup.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
  src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.component.ts
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
  src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.ts
  src/app/modules/rup/interfaces/elementoRUP.interface.ts
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
  src/app/modules/rup/services/elementosRUP.service.ts
Labels: revisar

#1889 RUP - Modifica ancho de listado de pacientes
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
Labels: Aprobado

#1892 feat(plex): actualiza dependencia necesarias para la nueva version de plex
  package-lock.json
  package.json
  src/app/apps/auth/components/login/login.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/components/auditoria/vincular-pacientes.html
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/inicio/inicio.html
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/components/puco/puco.html
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-carpetas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
  src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/punto-inicio/activar-app.html
  src/app/components/turnos/punto-inicio/paciente-search-turnos.html
  src/app/core/mpi/components/datos-contacto.html
  src/app/core/mpi/components/notas-paciente.html
  src/app/modules/estadisticas/components/citas/filtros.component.ts
  src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.ts
  src/app/modules/mpi/components/paciente-buscar.html
  src/app/modules/rup/components/core/_rup.scss
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/buscador.scss
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/internacion/puntoInicio-internacion.html
Labels: script

#1728 RUP: pto inicio lazy load pendientes
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado

#1873 CORE: tipoPrestacion.id por conceptId
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
  src/app/components/reportesDiarios/encabezadoReportesDiarios.component.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: Aprobado

#1774 INTERNACION - Listado de internación agrega filtros distintos para fechas de ingreso y egreso
  src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
Labels: Aprobado

#1894 fix(RUP):Se agrega required a ValorNumerico
  src/app/modules/rup/components/elementos/valorNumerico.component.ts
  src/app/modules/rup/components/elementos/valorNumerico.html
Labels: Aprobado

#1797 HUDS: Muestra nombre correcto de concepto de solicitud
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/huds/vistaSolicitudTop.html
Labels: Aprobado

#1843 INTERNACION - Quita el hardcodeo de colores en el estado de servicio
  package.json
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.scss
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.ts
Labels: Aprobado

#1821 INTERNACION - Agregar y editar una nota en las camas ocupadas
  package-lock.json
  package.json
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
Labels: revisar

#1862 feat(rup): configurar cuentas de email asociadas al efector
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/organizacion/organizacion-create-email.component.ts
  src/app/components/organizacion/organizacion-create-email.html
  src/app/components/organizacion/organizacion-lib.module.ts
  src/app/components/organizacion/organizacion.component.ts
  src/app/components/organizacion/organizacion.html
  src/app/components/organizacion/organizacion.module.ts
  src/app/modules/rup/components/ejecucion/modal-seleccion-email.html
Labels: Aprobado

#1907 chore(plex): @andes/plex@6.16.0
  package-lock.json
  package.json
Labels: test ok

#1833 ANGULAR 9 update
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
  src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
  src/app/apps/mitos/mitos.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
  src/app/components/turnos/punto-inicio/activar-app.component.ts
  src/app/core/mpi/components/busqueda-mpi.component.ts
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/datos-contacto.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/services/historialBusqueda.service.ts
  src/app/core/mpi/services/pacienteCache.service.ts
  src/app/directives/financiador-select-directive.ts
  src/app/directives/hover-class.directive.ts
  src/app/directives/organizacion-select.directive.ts
  src/app/directives/prestaciones-select.directive.ts
  src/app/directives/profesionales-select.directive.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/services/prestaciones.service.ts
  tsconfig.json
Labels: test ok

#1910 MPI: Dos fixes en auditoria y en la nota de un paciente
  src/app/components/auditoria/vincular-pacientes.component.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
Labels: test ok

#1886 MPI - re-validacion de pacientes
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#1891 MPI - Nuevo campo 'hora de nacimiento'
  src/app/core/mpi/components/datos-basicos.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/modules/mpi/components/paciente-panel.component.ts
Labels: test ok

#1911 RUP: permitir ver y continuar prestación si el usuario no tiene acceso a HUDS
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: test ok

#1913 feat(TOP): refactor visual en busqueda de paciente
  projects/shared/src/lib/components/popover-audit/popover-audit.component.ts
  projects/shared/src/lib/components/popover-audit/popover-audit.html
  projects/shared/src/lib/shared.module.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
  src/app/components/top/solicitudes/busquedaPaciente.component.ts
  src/app/components/top/solicitudes/busquedaPaciente.html
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.module.ts
  src/app/components/top/top.routing.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: test ok

#1909 fix(rup): odontrograma no se podia usar como segungo registro
  src/app/apps/auth/components/accept-disclaimer/modal-disclaimer.component.ts
  src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
Labels: test ok

#1898 Dashboard HUDS: mejora en filtro de prestaciones
  src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
  src/app/modules/estadisticas/components/rup/rup-pacientes.html
  src/app/modules/estadisticas/components/rup/rup-pacientes.scss
Labels: test ok

#1836 INTERNACION - Renombra 'cambiar UO' a 'pase de UO'
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
Labels: Aprobado

#1820 INTERNACION - Agrega UO origen al extra al hacer movimiento
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
Labels: revisar, test ok

#1916 fix(mapa-camas): handler null ubicacion
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
Labels: test ok

#1919 fix(TOP): no se visualizaban indicaciones de RUP
  src/app/components/top/solicitudes/detalleSolicitud.html
Labels: test ok

#1908 HUDS: rutas separadas de rup para huds
  src/app/app.routing.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
  src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/huds-lib.module.ts
  src/app/modules/rup/huds.module.ts
  src/app/modules/rup/rup.module.ts
  src/app/modules/rup/rup.routing.ts
Labels: script, test ok

#1896 feat(rup): buscador, mostrar fsn cuando no coicide con el term.
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/directives/snomed-link.ts
  src/app/modules/rup/directives/snomed-sinonimo.ts
  src/app/modules/rup/rup.module.ts
Labels: Aprobado, test ok

#1912 GDU: actualiza control de permisos de GDU
  src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
  src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
  src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
Labels: test ok

#1710 INTERNACIÓN - Agrega virtual scroll en tabla de camas
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: Aprobado, test ok

#1842 TOP: nueva solicitud traer prestaciones permitidas
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.html
Labels: test ok

#1915 CITAS - Corrige consulta repetitiva a api
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: test ok

#1922 chore(plex): v7.0.2
  package-lock.json
  package.json
Labels: test ok

#1872 MPI - Refactor visual auditoria
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/auditoria/auditoria.component.ts
  src/app/components/auditoria/auditoria.html
  src/app/components/auditoria/vincular-pacientes.component.ts
  src/app/components/auditoria/vincular-pacientes.html
  src/app/core/mpi/services/paciente.service.ts
  src/app/modules/auditoria/auditoria.module.ts
  src/app/modules/auditoria/auditoria.routing.ts
  src/app/modules/auditoria/component/auditoria-listado.component.ts
  src/app/modules/auditoria/component/auditoria-listado.html
  src/app/modules/auditoria/component/auditoria-listado.scss
  src/app/modules/auditoria/component/auditoria.component.ts
  src/app/modules/auditoria/component/auditoria.html
  src/app/modules/auditoria/component/auditoria.scss
  src/app/modules/auditoria/component/modal-correccion-paciente.component.ts
  src/app/modules/auditoria/component/modal-correccion-paciente.html
  src/app/modules/auditoria/component/modal-correccion-paciente.scss
  src/app/modules/auditoria/component/vincular-pacientes.component.ts
  src/app/modules/auditoria/component/vincular-pacientes.html
  src/app/modules/auditoria/component/vincular-pacientes.scss
Labels: test ok

#1918 fix(HUDS):error al visualizar prestaciones de un paciente inicialmente
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: Aprobado, test ok

#1900 feat(rup): flujo de datos al ejecutar un concepto
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
  src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.component.ts
  src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
  src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.ts
  src/app/modules/rup/components/elementos/rupers/texto-enriquecido/observaciones.component.ts
  src/app/modules/rup/services/ejecucion.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado, test ok

#1835 INTERNACION - Quitar "otros" de razon de alta y motivo de bloqueo
  src/app/apps/rup/mapa-camas/constantes-internacion.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-destino-generico/cama-destino-generico.component.ts
Labels: Aprobado, script

#1925 feat(core): check timezone
  src/app/apps/auth/components/login/login.component.ts
Labels: test ok

#1930 fix(citas): error obra social al autocitar
  src/app/components/turnos/autocitar/autocitar.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
Labels: test ok

#1929 INTERNACION - Controla el permiso de bloqueo de camas
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: Aprobado, test ok

#1931 fix(RUP): control del filtro actual para solicitudes
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: BugFix
