Repository andes/app, pull requests merged in 2020-04, with the labels that each got.

#1544 CITAS: Resetea los bloques de agenda dinámica
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: En revisión

#1557 CORE: directivas para plex-select
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/components/top/reglas/visualizacionReglas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/directives/financiador-select-directive.ts
  src/app/directives/organizacion-select.directive.ts
  src/app/directives/prestaciones-select.directive.ts
  src/app/directives/profesionales-select.directive.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/services/conceptos-turneables.service.ts
  tslint.json
Labels: En revisión

#1525 feat(RUP): Agregar al buscador el semantic Tag: fármaco de uso clínico
  .github/workflows/build.yml
  src/app/components/formularioTerapeutico/add-form-terapeutico.ts
  src/app/components/snomed/snomed-buscar.component.ts
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/interfaces/semantic-tag.type.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: En revisión

#1614 RUP: filtro por ámbito de origen en prestaciones de la historia de salud
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: En revisión

#1499 PRIVACIDAD: pantalla para aceptar disclaimer al iniciar sesión
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/apps/auth/auth.module.ts
  src/app/apps/auth/auth.routing.ts
  src/app/apps/auth/components/accept-disclaimer/acceptDisclaimer.component.ts
  src/app/apps/auth/components/accept-disclaimer/acceptDisclaimer.html
  src/app/apps/auth/components/accept-disclaimer/acceptDisclaimer.scss
  src/app/apps/auth/components/login/login.component.ts
  src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
  src/app/apps/gestor-usuarios/interfaces/IUsuario.ts
  src/app/interfaces/IDisclaimer.ts
  src/app/services/disclaimer.service.ts
  src/app/services/usuarios/usuario.service.ts
Labels: En revisión

#1621 feat(rup): agrega elemento de registro a las plantillas
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/elementos/informe.component.ts
Labels: En revisión

#1623 CITAS: Resetea turnos virtuales a 0
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: Aprobado, BugFix

#1534 RUP - Previsualización de informe de prestación
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Labels: En revisión

#1632 fix(mpi): Evita doble click en "Ignorar y Guardar"
  src/app/core/mpi/components/paciente-cru.component.ts
  src/app/core/mpi/components/paciente-cru.html
Labels: En revisión

#1630 Actualización de nombres de íconos de mdi
  package-lock.json
  package.json
  src/app/components/auditoria/prestacionPaciente/auditoria-prestacionPaciente.html
  src/app/components/inicio/inicio.html
  src/app/components/paciente/headerPaciente.scss
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/lista-espera/listaEspera.html
  src/app/components/turnos/punto-inicio/paciente-search-turnos.html
  src/styles.scss
Labels: En revisión, plex

#1618 CITAS: Arregla limpieza de numero de carpeta
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
Labels: BugFix

#1502 RUP: diagnostico principal en prestaciones con secciones
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/tsconfig.json
Labels: Aprobado

#1556 RUP: Corrige ruta de mapeo CIE10
  src/app/apps/mitos/services/snomed.service.ts
  src/app/modules/estadisticas/services/snomed.service.ts
Labels: Aprobado

#1619 TOP: oculta panel de prioridad al auditar otra solicitud
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
Labels: BugFix
