Repository andes/app, pull requests merged in 2020-03, with the labels that each got.

#1546 TOP: Asignación de una solicitud a un profesional al auditar
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/tsconfig.json
Labels: En revisión

#1590 Punto de inicio RUP: Quita tooltip de cantidad de solicitudes asignadas
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: BugFix, Urgente

#1567 refactor(mpi): crea modulo librería MPI
  src/app/app.module.ts
  src/app/components/paciente/paciente-detalle.html
  src/app/modules/mpi/components/demo.html
  src/app/modules/mpi/components/paciente-listado.html
  src/app/modules/mpi/components/paciente-panel.html
  src/app/modules/mpi/mpi-lib.module.ts
Labels: En revisión

#1593 Se actualiza template de PRs, se agrega recordatorio para correr tests
  .github/pull_request_template.md
  src/app/app.routing.ts
Labels: mejora

#1504 HUDS: Actualiza los conceptos en memoria
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: En revisión

#1516 fix(CITAS): arregla filtros por tipo de prestación al dar un turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: En revisión

#1526 feat(mpi): implementa plex-detail en paciente-detalle
  .circleci/config.yml
  package-lock.json
  package.json
  src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
  src/app/apps/gestor-usuarios/components/perfiles-detail.html
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.html
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.scss
  src/app/apps/gestor-usuarios/interfaces/IUsuario.ts
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
  src/app/apps/gestor-usuarios/views/usuarios-list.view.html
  src/app/components/paciente/paciente-detalle.html
  src/app/components/paciente/paciente-detalle.scss
  src/app/components/paciente/paciente-detalle.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/mpi/components/paciente-detalle.scss
  src/app/modules/mpi/components/paciente-detalle.ts
  src/app/modules/mpi/mpi-lib.module.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-estatico.html
  src/app/modules/rup/components/internacion/puntoInicio-internacion.html
  src/app/modules/rup/services/adjuntos.service.ts
  tslint.json
Labels: En revisión

#1520 LOGIN: control de huso horario al iniciar sesión
  src/app/apps/auth/components/login/login.component.ts
  src/app/apps/auth/components/login/login.html
Labels: Aprobado

#1597 RUP: Hot fix en limpieza de cache de paciente en validación de no nominalizada
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: BugFix, Urgente

#1415 RUP: Mejoras al crear Prestación fuera de Agenda
  package-lock.json
  package.json
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
Labels: En revisión

#1610 fix(rup-autocitación NUEVO): se agregan cambios para determinar autocitación
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
Labels: Aprobado

#1608 RUP - Se elimina scroll horizontal en resultados
  src/app/modules/rup/components/ejecucion/buscador.scss
Labels: Aprobado
