Repository andes/app, pull requests merged in 2020-07, with the labels that each got.

#1718 INTERNACION - Ver registros medicos en capa estadistica
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
Labels: Aprobado

#1758 HUDS: muestra fecha última evolución
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado

#1756 feat(RUP):se agrega seleccionar plantillas a sección
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
Labels: Aprobado

#1742 RUP: GET de reglas, cambia parámetros de ids de prestación a query auth
  package-lock.json
  package.json
  src/app/components/top/reglas/listaReglas.component.ts
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/services/conceptos-turneables.service.ts
Labels: Aprobado

#1581 RUP: información de solicitud en plex-help
  src/app/app.module.ts
  src/app/modules/rup/components/ejecucion/help-solicitud.component.ts
  src/app/modules/rup/components/ejecucion/help-solicitud.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Labels: Aprobado

#1771 INTERNACION - Guarda los filtros hasta que dure la sesion
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
Labels: Aprobado

#1729 RUP: Arregla duplicación solicitudes auditables
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado

#1717 RUP: Pto inicio, arreglo de filtrado por pacientes
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado

#1722 RUP: Evalúa condición requiereDiagnosticoPrincipal
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/interfaces/elementoRUP.interface.ts
Labels: Aprobado

#1780 INTERNACION - Incorporar los dias de estada en los censos con su calculo
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Labels: Aprobado

#1787 TOP: help de reglas en ejecución de prestación
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: Aprobado

#1620 feat(RUP): Se agrega árbol relaciones a la Ejecución
  src/app/app.module.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.scss
  src/app/modules/rup/components/huds/relaciones-rup.component.ts
  src/app/modules/rup/components/huds/relaciones-rup.html
  src/app/modules/rup/components/huds/relaciones-rup.scss
  src/app/modules/rup/services/huds.service.ts
Labels: Aprobado

#1579 HUDS: fix(modal motivo acceso): se corrige problema al cerrar con tecla ESC
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
Labels: Aprobado

#1793 HUDS: muestra tipo de prestación en registros de HUDS
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado

#1769 fix(huds): total de prestaciones
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: Aprobado

#1809 fix(TOP): Arregla duplicacion de prestacion al iniciar solicitud asignada
  src/app/components/top/solicitudes/prestacionSolicitud.component.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: BugFix, Urgente

#1730 RUP: ajustes UI/UX
  src/app/modules/rup/components/core/_rup.scss
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/components/huds/vistaProcedimiento.html
  src/app/modules/rup/components/huds/vistaRegistro.html
  src/app/modules/rup/components/variables.scss
Labels: Aprobado

#1783 RUP: se deja de auditar la agenda al validar la prestación para no nominalizadas
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: Aprobado

#1749 feat(huds): agrega eventos de google analytics
  src/app/components/inicio/inicio.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/shared/services/analytics.service.ts
Labels: Aprobado

#1522 RUP: Selecciona tab por defecto solo después de cargar todos los conceptos
  src/app/modules/rup/components/ejecucion/buscador.component.ts
Labels: Aprobado

#1799 feat(huds): filtrar por texto conceptos de la HUDS
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: revisar

#1814 feat(mapa-camas): registros filtros por unidad organizativa
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
Labels: Aprobado

#1816 feat(mapa-camas): quita filtro por ambito en registros medicos
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/modules/rup/components/huds/vistaPrestacion.html
Labels: Aprobado

#1806 INTERNACION - Agrega telefono y direccion en detalle de paciente
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.ts
Labels: Aprobado

#1694 RUP-Componente-Ultima-Fecha
  src/app/modules/rup/components/elementos/ultimaFecha.component.ts
  src/app/modules/rup/components/elementos/ultimaFecha.html
  src/app/modules/rup/elementos-rup.module.ts
Labels: Aprobado

#1791 RUP: Expandir ObservacionesComponent
  src/app/modules/rup/components/elementos/components/observaciones-modal.component.ts
  src/app/modules/rup/components/elementos/deprecated/informe.component.ts
  src/app/modules/rup/components/elementos/deprecated/informe.html
  src/app/modules/rup/components/elementos/rupers/texto-enriquecido/observaciones.component.ts
  src/app/modules/rup/components/elementos/rupers/texto-enriquecido/observaciones.html
  src/app/modules/rup/elementos-rup.module.ts
Labels: revisar

#1772 feat:(HUDS):se agrega grafico de temperatura a resumen-paciente
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.component.ts
Labels: Aprobado
