Repository andes/app, pull requests merged in 2021-09, with the labels that each got.

#2416 EP: audición de seguimientos
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.component.ts
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
  src/app/modules/epidemiologia/components/seguimiento/detalle-seguimiento/detalle-seguimiento.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
Labels: test ok, has conflicts

#2425 RUP - Seleccion de dosis despues de romper validacion
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2422 BI: arreglar dashboard TOP
  src/app/modules/estadisticas/components/citas/graficos.component.ts
  src/app/modules/estadisticas/components/top/top.html
Labels: test ok

#2429 Epidemiología - No se muestra boton editar
  src/app/modules/epidemiologia/pipes/checkEdit.pipe.ts
Labels: BugFix, test fail

#2413 VAC - Control reglas grupo poblacional
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
Labels: test ok

#2426 Dashboards CITAS - Turnos por Prestación/Profesional
  src/app/modules/estadisticas/components/citas/graficos.component.ts
  src/app/modules/estadisticas/components/citas/graficos.html
Labels: test ok

#2418 TM organizaciones: Agregar permiso global
  src/app/components/organizacion/organizacion.component.ts
  src/app/components/organizacion/organizacion.html
  src/app/services/organizacion.service.ts
Labels: test fail

#2433 fix(vacuna): filtra vacunas por código
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2432 VAC - Agrega nuevo estado de inscripción
  src/app/apps/vacunacion/components/detalle-inscripcion.html
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
Labels: test ok

#2419 EP: Asignar seguimiento a profesional
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.component.ts
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
  src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.component.ts
  src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.html
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
  src/app/modules/epidemiologia/contantes.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/epidemiologia/pipes/seguimientoFields.pipe.ts
  src/app/modules/epidemiologia/services/seguimiento-pacientes.service.ts
Labels: test ok

#2400 Visualizador: filtrar reportes c2 x organización
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
Labels: test ok

#2405 MISC (VAC) - Demanda rechazada
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: test ok

#2436 PDP - Visualización de datos en confirmación de turno
  projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.html
  projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.ts
  projects/portal/src/app/components/dar-turno/dar-turno.component.html
  projects/portal/src/app/components/dar-turno/dar-turno.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
Labels: test ok

#2404 Epidemiología - Agregar el profesional que confirmo y el que hisopo en la ficha covid 19
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: test ok

#2437 PDP - Visualizacion de turnos pendientes
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  projects/portal/src/app/services/turno.service.ts
Labels: test ok

#2440 EP: fixes mergeo asignacion
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/pipes/seguimientoFields.pipe.ts
Labels: test ok

#2442 EP: filtrar seguimientos activos
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
Labels: test ok

#2452 CITAS - No se habilita el boton liberar turnos desde el punto de inicio
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
Labels: BugFix, test ok

#2438 PDP - Guarda reporte de error
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/paciente-detalle.component.ts
  projects/portal/src/app/components/paciente-detalle.html
  src/app/services/logPaciente.service.ts
Labels: test ok

#2399 feat(CIT): consultorio virtual
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalle.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
  src/app/directives/feature-flag.directive.ts
  src/app/interfaces/turnos/IAgenda.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado, test ok

#2446 VAC: datos de certificado en detalle inscripción
  src/app/apps/vacunacion/components/detalle-inscripcion.component.ts
  src/app/apps/vacunacion/components/detalle-inscripcion.html
Labels: test ok

#2459 EPIDEMIOLOGÍA -Permitir seleccionar mas de una institucion en ficha COVID 19
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
Labels: test ok

#2458 BI Fix- No se limpian datos de leyenda
  src/app/modules/estadisticas/components/citas/graficos.component.ts
Labels: test ok

#2423 IPS: primera versión
  src/app/app.module.ts
  src/app/core/mpi/components/paciente.html
  src/app/core/mpi/services/paciente.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
  src/app/modules/rup/components/huds/rup-card/rup-card.component.html
  src/app/modules/rup/components/huds/rup-card/rup-card.component.ts
  src/app/modules/rup/components/huds/vista-ips.component.html
  src/app/modules/rup/components/huds/vista-ips.component.ts
  src/app/modules/rup/components/variables.scss
  src/app/modules/rup/huds-lib.module.ts
  src/app/modules/rup/rup-lib.module.ts
  src/app/modules/rup/services/dominios-nacionales.service.ts
  src/app/modules/rup/services/huds.service.ts
Labels: test ok

#2449 BI: mejora visual reportes c2
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
  src/app/components/reportes/reporteC2.component.ts
  src/app/components/reportes/reporteC2.html
Labels: changes requested, test ok

#2451 Turnos Prestaciones - Turnos prestaciones: agregar label "No se encontraron resultados"
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: test ok

#2460 rup: se corrige error al seleccionar una organización en solicitudes
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
Labels: Aprobado, test ok

#2445 BI: filtro de zona para reportes
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
Labels: test ok

#2454 BI: limpieza reporte diagnosticos
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/reportes/consultaDiagnostico.component.ts
  src/app/components/reportes/consultaDiagnostico.html
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
  src/app/services/turnos/agenda.service.ts
Labels: test ok

#2434 feat(mapa-camas): permisos para ver registros
  src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
Labels: Aprobado, test ok

#2455 VAC - Permitir borrar notas
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/components/notas.component.ts
  src/app/apps/vacunacion/components/notas.html
Labels: test ok

#2467 refactor(PER-49): filtro por fechas de control
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: test ok

#2441 Epidemiología - Crear filtro en seguimientos para pacientes asignados
  src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.html
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
Labels: test ok

#2456 MPI (Fix) - Error al visualizar fecha de nacimiento
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/mpi/components/paciente-listado.html
  src/app/modules/mpi/components/paciente-panel.html
Labels: test ok

#2468 fix(ips): handler de secciones vacías
  src/app/modules/rup/components/huds/vista-ips.component.html
  src/app/modules/rup/components/huds/vista-ips.component.ts
Labels: test ok

#2431 RUP: separa items por servicio intermedio
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/services/servicio-intermedio.service.ts
Labels: test ok

#2463 feat(RUP): acceso rapido a solicitud desde reglas
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/components/top/reglas/visualizacionReglas.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: Aprobado, test ok

#2473 GDU: mejoras usabilidad
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
  src/app/apps/gestor-usuarios/views/usuarios-list.view.html
Labels: test ok

#2474 GDU: mostrar en detalle si el profesional esta matriculado
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
  src/app/interfaces/IProfesional.ts
  src/app/services/profesional.service.ts
Labels: test ok

#2469 RUP: agrega concepto en select
  src/app/modules/rup/components/elementos/rupers/select-base.component.ts
Labels: Aprobado, test ok

#2470 Dashboard TOP (Fix) - Filtro de organización
  src/app/directives/organizacion-select.directive.ts
Labels: test ok

#2480 Turnos prestaciones: Actualizar limite de export huds en el buscador de turnos y prestacion
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
Labels: test ok

#2476 EP: habilitar priorización a seguimiento
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
Labels: test ok

#2465 CIT: validaciones de turnos ventanilla virtual
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: test ok

#2479 HUDS:error al cargar dos historias clínicas el mismo día
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
Labels: test ok

#2475 RUP: error,propiedad id indefinida
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Labels: test ok

#2471 Dashboard HUDS (Fix) - Filtros que se ocultan
  src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
  src/app/modules/estadisticas/components/rup/rup-pacientes.html
  src/app/modules/estadisticas/components/rup/rup-pacientes.scss
Labels: test ok
