Repository andes/app, pull requests merged in 2021-01, with the labels that each got.

#2097 fix(com): Filtra las derivaciones canceladas
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: test ok

#2088 feat(chore): activa ivy
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
  src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
  src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/modules/auditoria/component/auditoria.component.ts
  src/app/modules/auditoria/component/reporte-errores.component.ts
  src/app/modules/rup/components/elementos/autocitado.html
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
  src/app/modules/rup/components/elementos/talla.html
  src/app/modules/rup/components/elementos/temperatura.html
  tsconfig.json
Labels: test ok

#2095 feat(vacunacion): agrega control en dosis
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: En revisión

#2101 fix(rup): mapeo situaciones
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: test ok

#2100 COM: permitir modificar la prioridad
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/actualizar-estado.html
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/historial-derivacion.component.ts
  src/app/modules/com/components/historial-derivacion.html
  src/app/modules/com/components/punto-inicio.html
Labels: En revisión, test ok

#2099 COM: arreglo al actualizar datos simultaneamente
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/services/com/derivaciones.service.ts
Labels: En revisión, test ok

#2103 chore(plex): v7.11
  package-lock.json
  package.json
Labels: test ok

#2102 feat(rup): opción otros para checklist
  src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
  src/app/modules/rup/components/elementos/rupers/check-list/checklist.component.ts
  src/app/modules/rup/components/elementos/rupers/check-list/checklist.html
  src/app/modules/rup/elementos-rup.module.ts
  src/styles.scss
Labels: test ok

#2093 feat(login): Se agrega la posibilidad resetear la contraseña para los usuarios externos (no OneLogin)
  projects/auth/src/lib/auth.service.ts
  src/app/app.component.ts
  src/app/apps/auth/auth.module.ts
  src/app/apps/auth/auth.routing.ts
  src/app/apps/auth/components/forgot/forgot.component.ts
  src/app/apps/auth/components/forgot/forgot.html
  src/app/apps/auth/components/forgot/forgot.scss
  src/app/apps/auth/components/login/login.component.ts
  src/app/apps/auth/components/login/login.html
  src/app/apps/auth/components/recovery/recovery.component.ts
  src/app/apps/auth/components/recovery/recovery.html
  src/app/apps/auth/components/recovery/recovery.scss
  src/environments/apiKeyMaps.ts.example
  src/environments/environment.demo.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: test ok

#2098 TM: toast success en sincro sisa de organizacion
  src/app/components/organizacion/organizacion-create-update.component.ts
Labels: test ok

#2104 feat(mapa-camas): control request en ingresos
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: test ok

#2105 feat(rup): cambia a drive los archivos adjuntos
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.html
  src/app/shared/components/upload-file.component.ts
Labels: test ok

#2106 fix(mpi): foto paciente directiva
  src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
Labels: test ok

#2071 Guardia
  package-lock.json
  package.json
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/interfaces/mapa-camas.internface.ts
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
  src/app/apps/turnero/services/turnero.service.ts
  src/app/modules/rup/services/elementosRUP.service.ts
Labels: test ok

#2111 fix(rup): quita loads de esquemas y vacunas
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2110 CITAS: mostrar quien da el turno en revisión de agenda
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: test ok

#2107 feat(mapa-camas): agrega operacion para prestar y devolver camas
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.html
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok

#2112 mapa-camas: historial movimientos capa medica
  package-lock.json
  package.json
  projects/shared/src/lib/server/resource-base.ts
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: test ok

#2075 MPI - Adaptacion a rutas de core-v2/mpi
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/components/paciente.html
  src/app/core/mpi/components/relaciones-pacientes.component.ts
  src/app/core/mpi/components/relaciones-pacientes.html
  src/app/core/mpi/services/paciente-buscar.service.ts
  src/app/core/mpi/services/paciente.service.ts
  src/app/modules/auditoria/component/auditoria.component.ts
  src/app/modules/auditoria/component/reporte-errores.component.ts
  src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
  src/app/modules/mpi/interfaces/IPacienteMatch.inteface.ts
  src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
Labels: test ok

#2117 CORE - Carga de archivos con extensión en mayúscula
  src/app/shared/components/upload-file.component.ts
Labels: test ok
