Repository andes/app, pull requests merged in 2021-04, with the labels that each got.

#2192 VAC: mostrar los datos del inscripto al consultar por la inscripción
  src/app/apps/vacunacion/components/consulta.component.html
Labels: test ok

#2179 VACUNACIÓN: Agrega ayuda número de tramite
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
Labels: Aprobado, test ok

#2190 feat(vac): responsive, se mejora subtítulo ppal
  src/app/apps/vacunacion/components/consulta.component.html
  src/app/apps/vacunacion/components/consulta.component.ts
Labels: test ok

#2193 VAC: acceso a consultas de inscripción desde el formulario de registro
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2171 fix(virtual-scroll): corrige variables generales
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
Labels: Aprobado, test ok

#2172 MPI: se corrige error al mostrar badge "sin dni" en pacietes validados
  src/app/modules/mpi/components/paciente-detalle.component.ts
Labels: Aprobado, test ok

#2183 MPI - Fix revalidación de paciente
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2202 feat(VAC):agrega morbilidades a base de datos
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2203 FICHA-EPIDEMIOLOGICA: Actualizazión ficha COVID 19
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2191 feat(pdp): visualizar mis turnos actuales
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/paciente-detalle.component.ts
  projects/portal/src/app/components/paciente-detalle.html
  projects/portal/src/app/components/portal-menu/portal-menu.component.html
  projects/portal/src/app/components/portal-menu/portal-menu.component.ts
  projects/portal/src/app/components/portal-titulo/portal-titulo.component.html
  projects/portal/src/app/components/portal-titulo/portal-titulo.component.ts
  projects/portal/src/app/pages/login/login-portal-paciente.ts
  projects/portal/src/app/pages/mis-familiares/mis-familiares-detalle.component.html
  projects/portal/src/app/pages/mis-familiares/mis-familiares-detalle.component.ts
  projects/portal/src/app/pages/mis-familiares/mis-familiares.component.html
  projects/portal/src/app/pages/mis-familiares/mis-familiares.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalle.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente-main.component.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente-main.html
  projects/portal/src/app/pages/portal-paciente/portal-paciente.component.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente.html
  projects/portal/src/app/services/turno.service.ts
  projects/portal/src/styles.scss
Labels: changes requested

#2145 feat(IN): mapa-camas, visualizar camas agrupadas por sector
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
Labels: changes requested, test ok

#2207 INT: notifica ruta volver a mapa de camas
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
Labels: Aprobado, test ok

#2196 VAC - Asociar paciente a inscripción
  projects/portal/src/app/components/portal-titulo/portal-titulo.component.html
  src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
  src/app/apps/vacunacion/components/filtros-vacunacion.html
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/components/listado-inscriptos.scss
  src/app/apps/vacunacion/services/inscripcion.service.ts
Labels: test ok

#2198 VAC: permitir editar inscripciones
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
  src/app/apps/gestor-usuarios/gestor-usuarios.module.ts
  src/app/apps/gestor-usuarios/gestor-usuarios.providers.ts
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
  src/app/apps/vacunacion/components/editar-inscripcion.html
  src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/services/inscripcion.service.ts
  src/app/apps/vacunacion/vacunacion.module.ts
Labels: test ok

#2204 BI: biquery ficha epidemio
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: test ok

#2205 EPIDEMIOLOGÍA: Buscador de fichas epidemiologicas
  src/app/interfaces/IOrganizacion.ts
  src/app/interfaces/IZonaSanitaria.ts
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/epidemiologia/epidemiologia.routing.ts
  src/app/services/zonaSanitaria.service.ts
Labels: test ok

#2211 FICHA EPIDEMIOLÓGICA: Nuevas actualizaciones
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: has conflicts, test ok

#2208 fix(gestor-agendas): agrega aria-label en botoneras
  package-lock.json
  package.json
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, test ok

#2218 fix(gestor-usuarios): ajustes de perfiles
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
Labels: test fail

#2215 FICHA EPIDEMIOLOGICA: Modificación localidades
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2197 HUDS: visualiza fichas epidemiologicas
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/huds.module.ts
  src/app/modules/rup/services/huds.service.ts
Labels: test ok

#2224 EP: Fix nombre tipo de ficha en buscador
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok

#2216 VAC: editar datos básicos si no tiene paciente asociado
  src/app/apps/vacunacion/components/detalle-inscripcion.component.ts
  src/app/apps/vacunacion/components/detalle-inscripcion.html
  src/app/apps/vacunacion/components/editar-inscripcion.html
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/vacunacion.module.ts
Labels: test ok

#2223 VAC - Incluir vacunados en el listado
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/components/listado-inscriptos.scss
  src/app/apps/vacunacion/services/inscripcion.service.ts
  src/app/apps/vacunacion/vacunacion.module.ts
Labels: test ok

#2222 VAC - Agregar nota a una inscripción
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
Labels: test ok

#2126 COM: crea derivación como prestación
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/rup/services/elementosRUP.service.ts
Labels: test ok

#2227 MPI: Cambia patrón email de contactos
  src/app/core/mpi/components/datos-contacto.component.ts
Labels: test ok

#2234 fix(PDP):ordenar turnos de mas reciente a los mas viejos ultimos
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
Labels: test ok

#2233 feat(PDP):cache de la consulta de turnos, laboratorios y vacunas
  projects/portal/src/app/services/laboratorio.service.ts
  projects/portal/src/app/services/turno.service.ts
  projects/portal/src/app/services/vacuna.service.ts
Labels: test ok

#2236 fix(mapa-camas): varios fix internacion
  src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/modules/rup/services/plantillas.service.ts
Labels: test ok

#2232 VAC - Filtro por nombre y apellido
  src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
  src/app/apps/vacunacion/components/filtros-vacunacion.html
  src/app/apps/vacunacion/services/inscripcion.service.ts
Labels: test ok

#2180 FICHA-EPIDEMIOLÓGICA: Enviar datos de la ficha epidemiológica a MPI
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: test ok

#2219 EP: labels en form builder
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
Labels: test ok

#2229 EPIDEMIOLOGÍA: Scroll infinito buscador
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok

#2230 Events ficha epidemio
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2240 FICHA EPIDEMIOLOGICA: Actualizaciones
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: has conflicts, test ok

#2235 COM: unidad destino derivación
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/historial-derivacion.html
Labels: test ok

#2247 fix(mapa-camas): ajuste control fecha maximo de egreso
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test fail

#2169 TOP: Alertar al cargar solicitud repetida
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/modules/rup/components/ejecucion/buscador.component.ts
Labels: test ok

#2225 refactor(mpi): elimina rutas en desuso
  src/app/services/parentesco.service.ts
Labels: test ok

#2242 refactor(RUP): botón agregar paciente visible
  src/app/components/turnos/autocitar/dinamica.html
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#2241 RUP: limpieza de campos al cambiar vacuna/categoría
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2249 VAC: permitir cambiar el grupo de inscripciones
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
  src/app/apps/vacunacion/components/editar-inscripcion.html
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
Labels: changes requested, test ok
