Repository andes/app, pull requests merged in 2021-11, with the labels that each got.

#2504 BI: filtros por zonas en bi-queries
  src/app/modules/estadisticas/components/citas/filtros.component.ts
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: test ok

#2497 GDU: suma datos de matricula externa a detalle de usuario
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
  src/app/interfaces/IProfesional.ts
Labels: test ok

#2510 EP: filtro sin clasificación final
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok

#2509 Se agrega un delay para evitar que se haga una query po…
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: test ok

#2513 Error en la consola al abrir modal de envio de PDF
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
Labels: test ok

#2512 EP: parametrización clasificación final
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-contactos/ficha-epidemiologica-contactos.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/constantes.ts
  src/app/modules/epidemiologia/pipes/codigoSisa.pipe.ts
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: test fail

#2507 BI - Actualización plex-layout en dashboard
  src/app/modules/estadisticas/components/citas/citas.component.ts
  src/app/modules/estadisticas/components/citas/citas.html
  src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
  src/app/modules/estadisticas/components/rup/rup-pacientes.html
  src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts
  src/app/modules/estadisticas/components/tabla-2d/tabla-2d.html
  src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.html
  src/app/modules/estadisticas/components/top/top.component.ts
  src/app/modules/estadisticas/components/top/top.html
Labels: test ok

#2515 Epidemiologia - Se cierra collapse al editar/ver una ficha
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok, has conflicts

#2511 TM - Refactor de pantalla de configuración de servicios
  src/app/components/organizacion/organizacion-create-email.component.ts
  src/app/components/organizacion/organizacion-create-email.html
  src/app/components/organizacion/organizacion.html
  src/app/services/organizacion.service.ts
Labels: test ok

#2514 EP: eliminar ficha
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test fail

#2517 PER - Arreglo en columna de ausente
  package-lock.json
  package.json
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: test ok

#2516 MISC: se agrega componente de notas para usar en shared
  projects/shared/src/lib/components/notas/notas.component.ts
  projects/shared/src/lib/components/notas/notas.html
  projects/shared/src/lib/shared.module.ts
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/components/notas.component.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
  src/app/modules/perinatal/components/notas-embarazo.component.html
  src/app/modules/perinatal/components/notas-embarazo.component.ts
  src/app/modules/perinatal/perinatal.module.ts
Labels: test ok

#2505 VAC (Fix) - Avisa al usuario acerca de dosis ya aplicadas
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2478 rup: campos dinámicos para solicitudes
  angular.json
  projects/form-builder/README.md
  projects/form-builder/karma.conf.js
  projects/form-builder/ng-package.json
  projects/form-builder/package.json
  projects/form-builder/src/lib/form-builder-item/form-builder-item.component.html
  projects/form-builder/src/lib/form-builder-item/form-builder-item.component.ts
  projects/form-builder/src/lib/form-builder.module.ts
  projects/form-builder/src/lib/form-builder.service.ts
  projects/form-builder/src/lib/form-builder/form-builder.component.html
  projects/form-builder/src/lib/form-builder/form-builder.component.ts
  projects/form-builder/src/lib/interfaces.ts
  projects/form-builder/src/public-api.ts
  projects/form-builder/src/test.ts
  projects/form-builder/tsconfig.lib.json
  projects/form-builder/tsconfig.lib.prod.json
  projects/form-builder/tsconfig.spec.json
  projects/form-builder/tslint.json
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
  src/app/modules/rup/elementos-rup.module.ts
  tsconfig.json
Labels: test ok

#2483 mapa-camas: plan de indicaciones
  src/app/andes-common.module.ts
  src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
  src/app/apps/mitos/services/snomed.service.ts
  src/app/apps/rup/mapa-camas/components/plan-indicaciones-resumen.component.html
  src/app/apps/rup/mapa-camas/components/plan-indicaciones-resumen.component.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
  src/app/apps/rup/mapa-camas/services/maquina-estados.http.ts
  src/app/apps/rup/mapa-camas/services/plan-indicaciones-eventos.service.ts
  src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-color.pipes.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-nombre.pipe.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/medicamentos-busqueda-detalle/medicamentos-busqueda-detalle.component.html
  src/app/modules/rup/components/ejecucion/medicamentos-busqueda-detalle/medicamentos-busqueda-detalle.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento/prescripcion-medicamento.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento/prescripcion-medicamento.component.ts
  src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.scss
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/interfaces/elementoRUP.interface.ts
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
  src/app/modules/rup/pipes/elemento-rup-id.pipes.ts
  src/app/modules/rup/rup-lib.module.ts
  src/app/modules/rup/rup.module.ts
  src/app/modules/rup/services/conceptObserver.service.ts
  src/app/modules/rup/services/ejecucion.service.ts
  src/app/modules/rup/services/plantillas.service.ts
Labels: test ok

#2523 TM: nuevo campo observaciones en profesional
  src/app/components/profesional/profesional-create-update.component.ts
  src/app/components/profesional/profesional-create-update.html
Labels: test ok

#2518 Arreglando filtros en el modulo perinatal
  src/app/modules/perinatal/components/listado-perinatal.component.ts
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: test fail

#2531 IN (Fix) - Corregir los códigos de causa externa en el formulario de egreso - capa estadística
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test ok

#2527 PER: Agrega filtro por paciente en descarga CSV
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: test ok

#2534 GDU: confirmación al eliminar los permisos de una organización
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
Labels: test ok

#2535 feat(mapa-camas): navegación con flechas en resumen de internación
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
Labels: test ok

#2453 RUP - Molécula edad gestacional
  src/app/modules/rup/components/elementos/valorFecha.component.ts
  src/app/modules/rup/components/elementos/valorFecha.html
  src/app/modules/rup/elementos-rup.module.ts
Labels: test ok

#2521 Visualización de solicitudes en ejecución en RUP
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: changes done, test ok

#2533 IN (Fix) - Error capa médica días estada
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test ok

#2536 CIT: Guardar prestación en demanda rechazada
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: test ok
