Repository andes/app, pull requests merged in 2021-12, with the labels that each got.

#2500 VAC - Agrega control etareo segun dosis
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: changes done, test ok

#2532 MISC: refactor de componentes de campaña de salud
  src/app/apps/campaniaSalud/components/campania-create-update.html
  src/app/apps/campaniaSalud/components/campaniaSalud.component.ts
  src/app/apps/campaniaSalud/components/campaniaSalud.html
  src/app/apps/campaniaSalud/components/campaniaVisualizacion.component.ts
  src/app/apps/campaniaSalud/components/campaniaVisualizacion.html
Labels: test ok

#2530 MISC: refactor de pantalla de padrones
  src/app/components/puco/puco.component.ts
  src/app/components/puco/puco.html
Labels: Aprobado, test fail

#2537 TOP (Fix) - Eliminación de ultima regla
  src/app/components/top/reglas/reglas.component.html
  src/app/components/top/reglas/reglas.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: changes done, test ok

#2547 CIT: fix frecuentes duplicados
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: test ok

#2528 TM: refactor pantalla organizaciones
  src/app/components/organizacion/organizacion-create-update.component.ts
  src/app/components/organizacion/organizacion-create-update.html
  src/app/components/organizacion/organizacion.html
  src/app/components/organizacion/organizacion.scss
  src/app/core/mpi/components/georref-map.scss
Labels: test ok

#2529 feat(IN): mostrar registro de diagnostico al ingreso
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
Labels: test ok

#2543 citas: refactor visual header dar turno
  src/app/components/turnos/dar-turnos/calendario.scss
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: test ok

#2540 MISC - Visualización de las matriculas de un profesional
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/services/profesional.service.ts
  src/styles.scss
Labels: test fail

#2506 TOP - Suspensión de turno dado a solicitud
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
Labels: test ok

#2553 fix(rup): busqueda de elementoRUP por id en molecula
  src/app/modules/rup/components/core/rup.component.ts
Labels: test ok

#2545 feat(mapa-camas): plan-indicaciones, editar una indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: test ok

#2548 CITAS - Filtro por profesional en auditoría de fuera de agenda
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
  src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
Labels: changes done, test ok

#2552 MISC - Cambiar mensaje del toast al crear una nueva nota
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: changes requested, test fail

#2546 CIT - Ocultar botón disponible en agendas con turnos del dia/programados
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
Labels: test fail

#2541 CIT: dar sobreturno desde punto inicio
  src/app/components/turnos/dar-turnos/calendario.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
Labels: changes done, test fail

#2544 CITAS (Fix) - Turno en agenda no nominalizada ya auditada
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: changes requested, test fail

#2555 feat(mapa-camas): prescripcion de medicamentos internacion
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
  src/app/modules/rup/elementos-rup.module.ts
Labels: test fail

#2556 fix(mapa-camas): enfermeros no ven exploracion visual
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
Labels: test fail
