Repository andes/app, pull requests merged in 2021-08, with the labels that each got.

#2393 fix(inscripcion-vacunas): se quita requisito de certificado
  src/app/apps/vacunacion/components/editar-inscripcion.html
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
Labels: test ok

#2391 fix(in): se agrega idMovimiento al hacer un pase de servicio
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
Labels: test ok

#2384 feat(mapa-camas): listado-internación, deshacer egreso
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/environments/environment.dev.ts
Labels: test ok

#2380 PDP - Ajustes de visualización
  package-lock.json
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/paciente-detalle.component.ts
  projects/portal/src/app/components/paciente-detalle.html
  projects/portal/src/app/components/portal-menu/portal-menu.component.html
  projects/portal/src/app/components/portal-menu/portal-menu.component.ts
  projects/portal/src/app/components/portal-titulo/portal-titulo.component.html
  projects/portal/src/app/components/portal-titulo/portal-titulo.component.ts
  projects/portal/src/app/enums.ts
  projects/portal/src/app/interfaces/icard.ts
  projects/portal/src/app/pages/activar-cuenta/activar-cuenta.component.ts
  projects/portal/src/app/pages/login/login-portal-paciente.ts
  projects/portal/src/app/pages/mis-relaciones/mis-relaciones-detalle.component.html
  projects/portal/src/app/pages/mis-relaciones/mis-relaciones-detalle.component.ts
  projects/portal/src/app/pages/mis-relaciones/mis-relaciones.component.html
  projects/portal/src/app/pages/mis-relaciones/mis-relaciones.component.ts
  projects/portal/src/styles.scss
Labels: test ok

#2385 EP: refactor de historial de ficha
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/historial-ficha/historial-ficha.component.html
  src/app/modules/epidemiologia/components/historial-ficha/historial-ficha.component.ts
Labels: test ok

#2394 feat(TOP): Control permisos
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: test ok

#2137 feat(MISC): vista-prestacion boton editar
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.ts
  src/app/modules/rup/interfaces/prestacion.interface.ts
Labels: Aprobado, test ok

#2381 EP: clasificación final en HUDS
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: test ok

#2396 EP: fix duplicidad sidebars buscador
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
Labels: test ok

#2386 MPI - Permite letras en nro. de identificación de extranjero
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/core/mpi/components/datos-basicos.html
Labels: test ok

#2395 Buscador Epidemiología: Agregar filtro de clasificación final y columna idPcr
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok, has conflicts

#2352 VAC - Dación de turno desde la inscripción
  src/app/apps/vacunacion/components/gestion-turnos/dacion-turno.component.ts
  src/app/apps/vacunacion/components/gestion-turnos/dacion-turno.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/components/turnos/constantes.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
  src/app/services/conceptos-turneables.service.ts
Labels: changes done, test fail

#2366 VAC-88: Mostrar esquemas y condiciones de una dosis
  src/app/apps/vacunacion/components/lote/lote-esquemas.compone.ts
  src/app/apps/vacunacion/components/lote/lote-esquemas.component.ts
  src/app/apps/vacunacion/components/lote/lote-esquemas.html
  src/app/apps/vacunacion/components/lote/lote.component.html
  src/app/apps/vacunacion/components/lote/lote.component.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/services/vacunas.service.ts
Labels: changes done, test ok

#2390 PER - Descargar listado de controles
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
  src/app/services/documentos.service.ts
Labels: test ok

#2136 COM: llamar directamente a pestación
  projects/auth/src/lib/auth.service.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
Labels: test ok

#2349 MISC: componente semaforo priorizacion
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/actualizar-estado.html
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.scss
  src/app/modules/semaforo-priorizacion/components/scss/semaforo.scss
  src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
  src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.html
  src/app/modules/semaforo-priorizacion/interfaces/ISemaforo.ts
  src/app/modules/semaforo-priorizacion/service/semaforo.service.ts
Labels: test ok

#2389 feat(HUDS): se agrega estado solicitud y link a la prestación
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaProcedimiento.html
  src/app/modules/rup/components/huds/vistaProcedimiento.ts
  src/app/modules/rup/components/huds/vistaRegistro.html
  src/app/modules/rup/components/huds/vistaSolicitudTop.html
  src/app/modules/rup/components/huds/vistaSolicitudTop.ts
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Labels: Aprobado, test ok

#2406 TM - Error fsn undefined
  src/app/components/organizacion/organizacion-prestaciones.html
Labels: test fail

#2408 RUP - Invierte el orden de los sugeridos
  src/app/modules/rup/components/ejecucion/buscador.component.ts
Labels: test ok

#2402 VAC - Solicitudes de Campaña de Vacunación
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2379 Epidemiología: Save organización y actualizacion filtro clasificación
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2411 feat(huds): aplica estilos a timeline
  src/app/modules/rup/views/huds-timeline/huds-timeline.component.html
  src/app/modules/rup/views/huds-timeline/huds-timeline.component.ts
  src/app/modules/rup/views/huds-timeline/huds-timeline.scss
Labels: test ok

#2412 TM - Control de permisos cargando organizaciones del usuario
  src/app/components/organizacion/organizacion.component.ts
  src/app/components/organizacion/organizacion.html
Labels: test ok

#2407 VAC - FIX Registro de segundas dosis combinadas
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2414 Ficha Epidemiologica - Identidad autopercibida en ficha covid19
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: Aprobado, test ok

#2409 Epidmiología - Permitir editar fichas solo a usuarios con permisos en la organizacion en la que fue creada
  src/app/apps/gestor-usuarios/services/permisos.service.ts
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/epidemiologia/pipes/checkEdit.pipe.ts
Labels: test fail

#2417 Epidemiología - Espacio en blanco al final de la tabla de seguimiento
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
Labels: test fail
