Repository andes/app, pull requests merged in 2021-02, with the labels that each got.

#2120 MPI - Reemplaza busqueda match por get
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2123 Corrige asignacion de fotoId al obtenerlo de la validacion
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2129 CITAS - Fix solapamiento de turnos en agendas dinámicas
  src/app/components/turnos/autocitar/dinamica.component.ts
  src/app/services/turnos/turno.service.ts
Labels: test ok

#2130 chore(plex): actualiza plex a v7.13.0
  package-lock.json
  package.json
Labels: test ok

#2128 refactor(HUDS): se agrega filtro organizaciones
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: test ok

#2121 feat(vacunas): Se agrega la posiblidad de seleccionar el lote correspondiente
  src/app/modules/rup/components/elementos/vacunas.component.ts
  src/app/modules/rup/components/elementos/vacunas.html
  src/app/services/vacunas.service.ts
Labels: Aprobado, test ok

#2118 feat(COM): incluye traslados especiales
  package-lock.json
  package.json
  src/app/interfaces/IOrganizacion.ts
  src/app/interfaces/ITipoTraslado.ts
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
  src/app/modules/com/components/tipo-traslado/tipo-traslado.html
  src/app/modules/com/components/tipo-traslado/tipo-traslado.ts
  src/app/services/com/tipoTraslados.service.ts
Labels: test ok

#2127 TOP: poder guardar solicitudes sin profesional de origen
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/components/top/solicitudes/formNuevaSolicitud.html
Labels: test ok

#2074 INTERNACION - Nuevo pase de UO configurable por maquina de estados
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-destino-generico/cama-destino-generico.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok

#2115 CITAS - Activar/desactivar envío de sms de una agenda
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/interfaces/turnos/IAgenda.ts
  src/app/services/turnos/agenda.service.ts
Labels: test ok

#2125 TOP - Permite modificar profesional al dar turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: Aprobado, test ok

#2132 CITAS/RUP/TOP/COM - Aviso ante selección de paciente fallecido
  src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
  src/app/components/top/solicitudes/busquedaPaciente.component.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/turnos/autocitar/dinamica.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/services/paciente.service.ts
  src/app/modules/com/components/busqueda-paciente.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
Labels: changes requested, test ok

#2134 refactor(vista-prestacion): incorpora componentes plex
  src/app/modules/rup/components/core/_rup.scss
  src/app/modules/rup/components/huds/vistaPrestacion.html
Labels: test ok

#2114 feat(CITAS): se agrega permiso soloLectura
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
  src/app/components/turnos/dashboard/update-contacto-direccion.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: Aprobado, test ok

#2140 chore(portal): Initial commit
  angular.json
  projects/portal/browserslist
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.component.html
  projects/portal/src/app/app.component.scss
  projects/portal/src/app/app.component.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/home/home.component.html
  projects/portal/src/app/home/home.component.scss
  projects/portal/src/app/home/home.component.ts
  projects/portal/src/assets/.gitkeep
  projects/portal/src/environments/environment.prod.ts
  projects/portal/src/environments/environment.ts
  projects/portal/src/favicon.ico
  projects/portal/src/index.html
  projects/portal/src/main.ts
  projects/portal/src/polyfills.ts
  projects/portal/src/styles.scss
  projects/portal/tsconfig.app.json
  projects/portal/tslint.json
Labels: test ok

#2139 MPI - Agrega verificación de paciente activo antes de validar
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2143 feat(vacuna):Se agrega un check para dejar constancia que se realizó en domicilio
  src/app/modules/rup/components/elementos/vacunas.html
Labels: test ok

#2133 feat(mapa-camas): varios ajustes
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: test ok

#2113 CITAS - Dación de turnos con condiciones
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/interfaces/turnos/IAgenda.ts
  src/app/services/turnos/turno.service.ts
Labels: test ok

#2124 MPI - Salva valor de scan en paciente existente
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/core/mpi/components/busqueda-mpi.component.ts
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/services/paciente-buscar.service.ts
  src/app/core/mpi/services/pacienteCache.service.ts
Labels: test ok

#2141 MPI - Corrige edición de contactos en ventanilla
  src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
  src/app/components/turnos/dashboard/update-contacto-direccion.html
  src/app/core/mpi/components/datos-contacto.component.ts
  src/app/core/mpi/components/datos-contacto.html
Labels: Aprobado, test ok
