Repository andes/app, pull requests merged in 2021-03, with the labels that each got.

#2148 MPI - Bug actualizando contactos en ventanilla
  src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
  src/app/components/turnos/dashboard/update-contacto-direccion.html
Labels: Aprobado, test ok

#2147 fix(mapa-camas): filtrar sectores a partir de la unidad organizativa
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
Labels: Aprobado, test ok

#2135 refactor(RUP): se mantiene el formato de texto en las diferentes pest…
  src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
  src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
Labels: Aprobado, test ok

#2144 Prestamo de carpetas - Fix en filtro de prestaciones y actualización (uso) de componentes plex
  src/app/components/prestamosHC/historial/historial-hc.component.html
  src/app/components/prestamosHC/historial/historial-hc.component.ts
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/prestamosHC/prestamos-hc.component.ts
  src/app/components/prestamosHC/prestamos-hc.scss
  src/app/components/prestamosHC/prestamos/devolver-hc.component.html
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
  src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
  src/app/components/prestamosHC/solicitudes/prestar-hc.component.html
  src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.html
Labels: Aprobado, test ok

#2116 feat(MPI): documentos adjuntos paciente
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
  src/app/app.module.ts
  src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/core/mpi/components/busqueda-mpi.html
  src/app/core/mpi/components/documentos-paciente.component.ts
  src/app/core/mpi/components/documentos-paciente.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/components/paciente.html
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/directives/directives.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/mpi/mpi-lib.module.ts
  src/app/modules/rup/services/adjuntos.service.ts
  src/app/pipes/galeria.pipe.ts
Labels: Aprobado, test ok

#2142 CIT: new date fecha prestacion dinamica
  src/app/components/turnos/autocitar/dinamica.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado, test ok

#2149 Inscripción vacunas
  package-lock.json
  package.json
  src/app/app.routing.ts
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/interfaces/ICiudadano.ts
  src/app/apps/vacunacion/services/inscripcion.service.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/apps/vacunacion/vacunacion.routing.ts
  src/app/services/grupo-poblacional.service.ts
  src/app/services/profesion.service.ts
  src/assets/img/ficha-corregida-CUD.png
  src/environments/apiKeyMaps.ts.example
  src/environments/environment.demo.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: test ok

#2131 EPIDEMIOLOGIA: Form buillder y punto de inicio de ficha epidemiologica
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.routing.ts
  src/app/components/inicio/inicio.component.ts
  src/app/directives/select-search.directive.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/epidemiologia/epidemiologia.routing.ts
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
  src/app/modules/forms-builder/components/forms-list/forms-list.component.html
  src/app/modules/forms-builder/components/forms-list/forms-list.component.ts
  src/app/modules/forms-builder/forms.module.ts
  src/app/modules/forms-builder/forms.routing.ts
  src/app/modules/forms-builder/resolver/forms.resolver.ts
  src/app/modules/forms-builder/services/form.service.ts
  src/app/modules/forms-builder/services/resources.service.ts
  src/app/services/select-search.service.ts
Labels: test ok

#2154 fix(ficha-epidemiologica): agregamos información que falta en el test
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2152 Inscripción Vacunas: Quita restricción a grupo discapacidad para limite de edad máxima
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2146 MPI - Reemplaza toast de ciudadano no encontrado
  src/app/core/mpi/components/paciente.component.ts
Labels: Aprobado, test ok

#2150 TURNOS-PRESTACIONES: Agregar máximo permitido al exportarHuds
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: test ok

#2151 feat(rup): ajuste visual botones en ejecucion
  src/app/modules/rup/components/ejecucion/help-solicitud.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: test ok

#2160 fix(RUP): Vacunas covid control interdosis
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2158 VAC - Selección de grupo poblacional por url
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/vacunacion.routing.ts
Labels: test ok

#2155 VAC: variable para deshabilitar control de captcha
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/environments/apiKeyMaps.ts.example
Labels: test ok

#2164 fix(VAC): Agrega la selección de factores de riesgo en la inscripción
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/interfaces/ICiudadano.ts
Labels: test ok

#2165 feat(VAC): agrega imágenes de número de trámite
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/interfaces/ICiudadano.ts
  src/assets/img/andes-dni-dorso.jpg
  src/assets/img/andes-dni-frente.jpg
Labels: test ok

#2157 VACUNACIÓN: Formulario de inscripción profesionales certificados
  projects/shared/src/lib/server/options.ts
  projects/shared/src/lib/server/server.service.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
  src/app/services/profesional.service.ts
  src/app/services/usuarios/usuario.service.ts
Labels: test ok

#2175 VAC: arreglo de seteo de fechas cuando el grupo viene por parámetro
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2177 feat(inscripcion): agrega control de edad mayor a 18 en grupos faltantes
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2168 fix(CITAS):cambio de lugar de input en turnos paciente
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
Labels: test ok

#2163 Portal de pacientes - Login y home
  package-lock.json
  package.json
  projects/auth/src/lib/auth.service.ts
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.component.html
  projects/portal/src/app/app.component.scss
  projects/portal/src/app/app.component.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/app.routings-guard.class.ts
  projects/portal/src/app/components/paciente-detalle.component.ts
  projects/portal/src/app/components/paciente-detalle.html
  projects/portal/src/app/home/home.component.html
  projects/portal/src/app/home/home.component.scss
  projects/portal/src/app/home/home.component.ts
  projects/portal/src/app/pages/login/login-portal-paciente.component.html
  projects/portal/src/app/pages/login/login-portal-paciente.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente-main.component.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente-main.html
  projects/portal/src/app/pages/portal-paciente/portal-paciente.component.ts
  projects/portal/src/app/pages/portal-paciente/portal-paciente.html
  projects/portal/src/app/services/paciente-portal.service.ts
  projects/portal/src/environments/environment.ts
  projects/portal/src/index.html
  projects/portal/src/main.ts
  projects/portal/tsconfig.app.json
  projects/portal/tslint.json
  projects/shared/src/lib/server/server.service.ts
  projects/shared/src/lib/shared.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
Labels: test ok

#2181 fix(VAC): agrega variable para resguardar los factores de riesgo seleccionados
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2173 fix(rup): controles de fechas
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: test ok

#2176 feat(plex): v7.14
  package-lock.json
  package.json
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
  src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.html
  src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.ts
  src/app/components/top/solicitudes/anularSolicitud.component.ts
  src/app/components/top/solicitudes/anularSolicitud.html
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.html
Labels: test ok

#2185 fix(citas): type permisos
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: test ok

#2178 COM: uso de ruta de drive para leer archivos del COM
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/historial-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/services/com/adjuntos.service.ts
  src/app/services/com/derivaciones.service.ts
Labels: test ok

#2166 TOP: se suma estado ejecución a filtros en solicitudes
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: test fail

#2186 feat(top): control de fechas vacias
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: test ok

#2161 VAC: pantalla para consultar el estado de inscripciones
  src/app/apps/vacunacion/components/consulta.component.html
  src/app/apps/vacunacion/components/consulta.component.ts
  src/app/apps/vacunacion/services/inscripcion.service.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/apps/vacunacion/vacunacion.routing.ts
Labels: changes requested, test ok

#2156 VAC - Listado de inscriptos
  projects/shared/src/lib/directives/autosave.directives.ts
  src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
  src/app/apps/vacunacion/components/filtros-vacunacion.html
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
  src/app/apps/vacunacion/components/listado-inscriptos.scss
  src/app/apps/vacunacion/services/inscripcion.service.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/apps/vacunacion/vacunacion.routing.ts
Labels: test ok

#2194 feat(inscripcion): Agrega morbilidades
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test fail

#2184 feat(CITAS):Imprimir agenda
  src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
  src/app/services/documentos.service.ts
Labels: test ok
