Repository andes/app, pull requests merged in 2021-06, with the labels that each got.

#2295 MPI:Nuevo atriburo idPacientePrincipal en paciente para linkeo
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/core/mpi/services/paciente.service.ts
Labels: test ok

#2305 BUSCADOR EPIDEMIO: Fix doble request
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: test ok

#2297 FICHA EPIDEMIOLÓGICA: Loader en buscador de pacientes
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: test ok

#2309 feat(inscripcion): agrega control de edad por reglas
  src/app/apps/vacunacion/components/inscripcion.component.ts
Labels: test ok

#2307 feat(mapa-camas): sincronizar plex-datetime en resumen internación
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
Labels: test ok

#2302 FICHA EPIDEMIOLÓGICA: field activo localidades
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2308 IN - Agrega fecha de ingreso en censo diario
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
Labels: test ok

#2296 COM: asignar origen desde org COM
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
Labels: changes done, test ok

#2311 fix(inscripcion): agrega grupo sin FR
  src/app/apps/vacunacion/components/consulta.component.html
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Labels: test ok

#2283 INT - Agregar columna 'unidad organizativa'
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
  src/app/modules/rup/interfaces/prestacion.interface.ts
Labels: changes done, test ok

#2312 FICHA EPIDEMIOLOGICA: Check días
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: test ok

#2238 feat(login): se implementa v0.1
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/logo-portal-paciente/logo-portal-paciente.component.html
  projects/portal/src/app/logo-portal-paciente/logo-portal-paciente.component.scss
  projects/portal/src/app/logo-portal-paciente/logo-portal-paciente.component.ts
  projects/portal/src/app/pages/login/login-portal-paciente.component.html
  projects/portal/src/app/pages/login/login-portal-paciente.scss
  projects/portal/src/app/pages/login/login-portal-paciente.ts
  projects/portal/src/assets/logo-portal-paciente.svg
Labels: test ok

#2315 IN - Fix dias de estada totales en censo mensual
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Labels: test ok

#2277 VAC: desvincular paciente de inscripción
  src/app/apps/vacunacion/components/listado-inscriptos.component.ts
  src/app/apps/vacunacion/components/listado-inscriptos.html
Labels: test ok

#2317 mapa-camas: implementa plex-table en listado de internación
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
Labels: changes done, test ok

#2310 IN - Nueva opción 'otro' en tipo de egreso y organización destino
  src/app/apps/rup/mapa-camas/constantes-internacion.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
Labels: changes done, test ok

#2306 feat(com): Se agrega la posibilidad de asignar dispositivo de oxigeno al proceso de derivación
  package-lock.json
  package.json
  src/app/modules/com/com.module.ts
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/actualizar-estado.html
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/detalle-derivacion.html
  src/app/modules/com/components/historial-derivacion.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.html
  src/app/modules/dispositivo/dispositivo.component.ts
  src/app/modules/dispositivo/dispositivo.html
  src/app/services/dispositivo/dispositivo.service.ts
Labels: test ok

#2314 FICHA EPIDEMIOLÓGICA: Nuevo campo residencias
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2303 Mostrar submódulos como módulos
  src/app/components/inicio/inicio.component.ts
  src/app/components/inicio/inicio.html
  src/app/interfaces/novedades/IModulo.interface.ts
Labels: test ok

#2319 Listado-internación - Visualizar detalle de registros
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: test ok

#2320 chore(plex): v7.18.1
  package-lock.json
  package.json
Labels: test ok

#2313 feat(mapa-camas):filtros por unidad organizativa y paciente
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.html
  src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
Labels: test ok

#2324 fix(COM): Fix error en merge para instituciones de com
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
Labels: BugFix, test ok

#2321 refactor(PER): Alertas Fecha Fin Embarazo
  src/app/modules/perinatal/components/alertas-perinatal.component.ts
  src/app/modules/perinatal/components/detalle-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: test ok

#2327 Mapa-camas: Actualiza unidad organizativa original al editar una cama
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
Labels: changes done, test ok

#2326 Resumen-internación - Limpia header de paciente al volver
  src/app/app.routing.ts
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
Labels: test ok

#2325 COM: remover COM de origen
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
Labels: test ok

#2333 Turnos prestaciones: Disabled boton exportar
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: test ok

#2331 Resumen-internación - Evita recargar prestación nuevamente
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/modules/rup/components/huds/vistaPrestacion.ts
  src/environments/environment.dev.ts
Labels: test ok

#2323 rup: conceptos requeridos dinámicos
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/services/elementosRUP.service.ts
Labels: test ok

#2334 feat(COM): Se le agrega nuevo color para identificar prioridades intermedias, se le agrega también el filtro de ordenamiento
  src/app/modules/com/components/actualizar-estado.component.ts
  src/app/modules/com/components/detalle-derivacion.component.ts
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/com/components/punto-inicio.scss
  src/app/modules/com/services/punto-inicio.service.ts
Labels: test ok

#2281 MPI: cargar lugar de nacimiento a paciente
  src/app/core/mpi/components/datos-contacto.component.ts
  src/app/core/mpi/components/datos-contacto.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/interfaces/IUbicacion.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
Labels: changes done, test ok

#2338 fix(VAC): Editar la inscripción
  src/app/apps/vacunacion/components/listado-inscriptos.html
Labels: test ok

#2339 feat(VAC):agrega nuevo grupo de personas gestantes
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Labels: test ok

#2340 FICHA EPIDEMIOLOGICA: Fix secciones
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2330 fix(rup): muestra resultado de la formula
  src/app/modules/rup/components/elementos/FormulaBase.component.ts
  src/app/modules/rup/components/elementos/FormulaBase.html
  src/app/modules/rup/components/formulas/index.ts
Labels: test ok

#2341 IN - Elimina controles de movimientos para préstamos de camas
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok

#2301 IN - Anular internación con varios movimientos
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
Labels: changes done, test ok

#2342 Ficha Epidemiologica: Ficha parcial
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: test ok

#2347 fix(huds): evoluciones
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/huds/vistaContextoPrestacion.html
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test ok

#2322 feat(rup): permisos especiales para validar
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#2345 fix(VAC):sacar dos precauciones de la inscripción de vacunación
  src/app/apps/vacunacion/components/detalle-inscripcion.html
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
  src/app/apps/vacunacion/interfaces/ICiudadano.ts
Labels: test ok

#2304 feat(VAC-77) Mostrar las vacunas con sus lotes y agregar un nuevo lote
  src/app/apps/vacunacion/components/lote/lote.component.html
  src/app/apps/vacunacion/components/lote/lote.component.ts
  src/app/apps/vacunacion/vacunacion.module.ts
  src/app/apps/vacunacion/vacunacion.routing.ts
  src/app/services/vacunas.service.ts
Labels: changes done, test ok

#2343 IN - Fix fecha 'hoy' en egreso de paciente
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test ok

#2336 Punto inicio Andes: mejoras visuales cuando hay 4 o más submódulos
  src/app/components/inicio/inicio.component.ts
  src/app/components/inicio/inicio.html
  src/app/components/inicio/inicio.scss
Labels: test ok
