Repository andes/app, pull requests merged in 2021-07, with the labels that each got.

#2350 feat(VAC):agrega registro de llamados
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
Labels: test ok

#2351 refactor(MISC-173) modificando campañas de salud
  src/app/apps/campaniaSalud/components/campania-create-update.component.ts
Labels: test fail

#2329 PORTAL DE PACIENTE : Solicitar turno
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.html
  projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.ts
  projects/portal/src/app/components/dar-turno/dar-turno.component.html
  projects/portal/src/app/components/dar-turno/dar-turno.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  projects/portal/src/app/services/turno.service.ts
  src/app/services/turnos/agenda.service.ts
Labels: test ok

#2332 Integracion seguimiento
  src/app/app.module.ts
  src/app/modules/com/components/punto-inicio.component.ts
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-contactos/ficha-epidemiologica-contactos.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-contactos/ficha-epidemiologica-contactos.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.component.ts
  src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
  src/app/modules/epidemiologia/components/seguimiento/detalle-seguimiento/detalle-seguimiento.component.ts
  src/app/modules/epidemiologia/components/seguimiento/detalle-seguimiento/detalle-seguimiento.html
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
  src/app/modules/epidemiologia/contantes.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/epidemiologia/epidemiologia.routing.ts
  src/app/modules/epidemiologia/pipes/seguimientoFields.pipe.ts
  src/app/modules/epidemiologia/services/seguimiento-pacientes.service.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/seguimiento-paciente/seguimientoPaciente.component.ts
  src/app/modules/rup/components/ejecucion/seguimiento-paciente/seguimientoPaciente.html
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.ts
  src/app/modules/rup/huds-lib.module.ts
  src/app/modules/rup/interfaces/seguimientoPaciente.interface.ts
  src/app/modules/rup/services/elementosRUP.service.ts
  src/app/modules/rup/services/seguimientoPaciente.service.ts
  src/app/utils/enumerados.ts
Labels: test ok

#2318 Mapa-camas - Días de estada en el listado
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/interfaces/mapa-camas.internface.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
Labels: changes done, test ok

#2291 pacs: primera version
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
  src/app/components/top/reglas/reglas.component.ts
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/calendario.component.ts
  src/app/components/turnos/dar-turnos/calendario.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
  src/app/modules/rup/components/ejecucion/help-solicitud.html
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.ts
  src/app/modules/rup/components/servicio-intermedio/servicio-intermedio-alta.component.html
  src/app/modules/rup/components/servicio-intermedio/servicio-intermedio-alta.component.ts
  src/app/modules/rup/interfaces/prestacion.interface.ts
  src/app/modules/rup/rup.module.ts
  src/app/modules/rup/services/huds.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/modules/rup/services/servicio-intermedio.service.ts
Labels: has conflicts, test fail

#2355 feat(rup): romper validacion si tengo permisos
  projects/auth/src/lib/auth.service.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Labels: test ok

#2360 HUDS: Fix Mostrar ficha epidemio
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: BugFix, Urgente, test fail

#2358 IN - Fix filtrar sectores sin camas activas
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok

#2356 EP: fix duplicidad de save
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
Labels: test ok

#2348 Ficha Epidemio: Disabled carga parcial ficha
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Labels: test ok

#2362 feat(mapa-camas): retry operation
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
Labels: test ok

#2359 vacunas: optimización de llamados a la api
  src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
  src/app/apps/vacunacion/components/filtros-vacunacion.html
  src/app/apps/vacunacion/services/inscripcion.service.ts
Labels: test ok

#2328 feat(PDP): Actualizar datos personales
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/paciente-detalle.html
  projects/portal/src/app/pages/mis-datos-personales/mis-datos-personales.component.html
  projects/portal/src/app/pages/mis-datos-personales/mis-datos-personales.component.ts
  projects/portal/src/app/pages/mis-familiares/mis-familiares.component.ts
  projects/portal/src/app/services/paciente-portal.service.ts
Labels: changes done, test ok

#2365 fix(mapa-camas): hisotrial de un año maxima
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
Labels: test ok

#2361 HUDS: fix ordenar prestaciones
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/environments/environment.dev.ts
Labels: test ok

#2337 feat(ficha): Se agrega el filtrado por clasificación en search de la ficha
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Labels: has conflicts, test ok

#2353 EP: resize sidebar paciente
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
Labels: test ok

#2357 Ficha Epidemiologica: regex pcr
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2368 Ficha Epidemiologica: Caso asintomático
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2367 fix(MISC-166): Bug al cargar numero de carpeta a un paciente
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
Labels: changes requested, test ok

#2335 Mapa-camas - Marcar una internación como censable aunque la cama no lo sea
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Labels: test ok

#2369 RUP - Guarda prestaciones modificadas y anuladas en nueva colección
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test fail

#2354 MPI - Seteo de atributos en paciente-detalle
  src/app/components/paciente/headerPaciente.html
  src/app/components/paciente/headerPaciente.scss
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
Labels: changes done, test ok

#2375 COM: color prioridad intermedia
  src/app/utils/enumerados.ts
Labels: BugFix, test ok

#2363 TM - Cargar firma de profesional fuera de matriculaciones
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/profesional/firma/firma-profesional.component.ts
  src/app/components/profesional/firma/firma-profesional.html
  src/app/components/profesional/firma/firma-profesional.scss
  src/app/components/profesional/profesional-create-update.component.ts
  src/app/components/profesional/profesional-create-update.html
  src/app/components/profesional/profesional.html
  src/app/services/profesional.service.ts
Labels: test ok

#2292 feat(pacs): mapa de agendas con colores
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.html
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-mes.component.html
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-mes.component.ts
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-semana.component.html
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda-semana.component.ts
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agenda.module.ts
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.html
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.component.ts
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.scss
  src/app/components/turnos/gestor-agendas/mapa-agendas/mapa-agendas.service.ts
Labels: Aprobado, test ok

#2370 feat(VAC):inscripcion para extranjeros
  src/app/apps/vacunacion/components/inscripcion.component.html
  src/app/apps/vacunacion/components/inscripcion.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
  src/app/apps/vacunacion/interfaces/ICiudadano.ts
Labels: test ok

#2383 fix(citas): corrige error de filtros
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: test ok

#2382 chore(plex): v7.18.2
  package-lock.json
  package.json
Labels: test ok

#2344 Vacunación - Registrar fecha de próximo llamado
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
Labels: test ok

#2378 Epidemiología: Elimina input vista-prestacion
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.ts
Labels: test ok

#2373 feat(PER-32): agregar filtros en modulo perinatal
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
  src/app/modules/perinatal/perinatal.module.ts
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: changes done, test ok

#2371 feat(VAC):agrega boton para desasignar inscriptos
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
  src/app/apps/vacunacion/services/inscripcion.service.ts
Labels: test ok

#2374 feat(VAC):control de edades en nueva inscripción
  src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.component.ts
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Labels: test ok

#2387 Epidemiología: Nuevo regex idPcr
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2377 EP fix: visualizar ficha en huds de rup
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/rup.module.ts
Labels: BugFix, test ok

#2388 fix(VAC):número identificacion en caso documento en blanco
  src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Labels: test ok

#2392 EP: buscador fecha tipo date
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
Labels: test ok
