Repository andes/app, pull requests merged in 2022-01, with the labels that each got.

#2428 RUP: turno Multiprestacion
  src/app/interfaces/ITipoPrestacion.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/services/prestaciones.service.ts
Labels: test ok

#2562 fix(rup): permisos turnos
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: test ok

#2563 Epidemiología - Dejar readonly select muestra de pcr
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
Labels: test ok

#2560 RUP: continuar registro no nominalizada
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#2564 Epidemiología - Modificar restriccion antigeno no reactivo
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test fail

#2561 Epidemiolgia - Error en semana epidemiológica
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Labels: test ok

#2565 fix(rup): controles de permisos
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#2525 IN - Registro de uso de respirador en colección internacionPacienteResumen
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/huds.module.ts
  src/app/modules/rup/rup.module.ts
Labels: changes done, test ok

#2567 VAC: se visualizan todas las dosis de una vacunas con excepciones
  src/app/modules/rup/components/elementos/vacunas.component.ts
Labels: test ok

#2550 RUP (Fix) - Poder editar valor de edad gestacional
  src/app/modules/rup/components/elementos/FormulaBase.component.ts
  src/app/modules/rup/components/elementos/FormulaBase.html
  src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Labels: changes done, test ok

#2568 MISC - filtro multiple de obras sociales
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: test ok

#2557 feat(in): nueva capa 'interconsultores'
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/interfaces/ITipoPrestacion.ts
Labels: test ok

#2569 Epidemiología - Mostrar en la ficha el estado de vacunacion del paciente
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/services/pacientes-vacunas.service.ts
Labels: test ok

#2487 PDP - Demanda insastifecha
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/dar-turno/dar-turno.component.html
  projects/portal/src/app/components/dar-turno/dar-turno.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos-detalle.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  projects/portal/src/app/pages/mis-turnos/notificar-necesidad.component.html
  projects/portal/src/app/pages/mis-turnos/notificar-necesidad.component.ts
Labels: test ok

#2570 MPI - Domicilio legal de un paciente
  src/app/core/mpi/components/datos-contacto.component.ts
Labels: test ok

#2571 feat(mapa-camas): ajustes a prescripción de medicamentos
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
Labels: test ok

#2572 feat(bi-query): campo key configurable
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: test ok

#2549 CIT - Agregar botón de generar comprobante en el buscador de turnos y prestaciones
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
Labels: changes done, test ok

#2577 fix(mapa-camas): errores egresos
  .eslintrc.js
  projects/form-builder/src/lib/form-builder-item/form-builder-item.component.ts
  projects/form-builder/src/lib/form-builder.module.ts
  projects/form-builder/src/lib/form-builder/form-builder.component.ts
  projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/integridad/integridad.service.ts
  src/app/apps/vacunacion/components/editar-inscripcion.component.ts
  src/app/components/organizacion/organizacion-create-email.component.ts
  src/app/components/organizacion/organizacion-create-update.component.ts
  src/app/modules/rup/components/huds/listado-internacion-huds.component.ts
  src/app/services/especialidad.service.ts
  src/app/services/formTerapeutico/formTerapeutico.service.ts
  src/app/services/xlsx.service.ts
Labels: test ok
