Repository andes/app, pull requests merged in 2022-09, with the labels that each got.

#2728 IN: listado internación rango fechas
  projects/shared/src/lib/server/resource-base.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
Labels: test fail, publicar

#2697 RUP: Se agregan nuevas condiciones en un componente de seleccion Binaria
  src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
  src/app/modules/rup/components/elementos/seleccionBinaria.html
  src/app/modules/rup/elementos-rup.module.ts
  src/app/modules/rup/pipes/elemento-rup-valor.pipes.ts
Labels: test ok, publicar

#2519 TM - ABM para configuración de internación
  src/app/apps/rup/mapa-camas/services/maquina-estados.http.ts
  src/app/components/organizacion/configuracion-internacion.component.ts
  src/app/components/organizacion/configuracion-internacion.html
  src/app/components/organizacion/organizacion.component.ts
  src/app/components/organizacion/organizacion.html
  src/app/components/organizacion/organizacion.module.ts
Labels: test ok, publicar

#2620 RUP: dar sobreturno no dinamica nominalizada en pto inicio
  src/app/components/turnos/autocitar/dinamica.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/rup.module.ts
Labels: changes requested, test fail, publicar

#2700 IN - Agregar restricciones de visualizacion en capa interconsultores
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test fail
