Repository andes/app, pull requests merged in 2022-12, with the labels that each got.

#2757 TOP - Listado reglas
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/components/top/reglas/visualizacionReglas.html
Labels: changes done, test fail

#2783 CIT - Visualizar badge No asistió en historial de turnos
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/turnos-paciente.html
Labels: changes done, test ok

#2765 CITAS - Filtro por multiples prestaciones y revision filtros fechas.
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: changes done, test ok

#2791 Fix en listado de reglas TOP/RUP
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: test ok

#2787 RUP - No se visualiza botón iniciar prestación
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Labels: test ok, publicar

#2702 IN - Error al cambiar de cama
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
Labels: changes done, test fail, publicar

#2745 PER - Cantidad de embarazos
  src/app/modules/perinatal/components/detalle-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.html
Labels: test ok

#2795 TOP: Corrige visualización de reglas en RUP ejecución
  src/app/components/top/reglas/visualizacionReglas.component.ts
Labels: test fail
