Repository andes/app, pull requests merged in 2022-06, with the labels that each got.

#2660 IN - Censo mensual - porcentajes
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Labels: test ok

#2637 CIT - Agregar filtro por ambito ambulatorio al crear una agenda
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/directives/prestaciones-select.directive.ts
  src/app/services/conceptos-turneables.service.ts
Labels: test ok

#2645 CITAS - Actualización de gestor de agendas
  src/app/app.module.ts
  src/app/components/turnos/citas.module.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.scss
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html
  src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
  src/app/components/turnos/gestor-agendas/pipes/botonesAgendaGeneral.pipe.ts
Labels: test ok, has conflicts

#2650 CIT - filtrar por ámbito ambulatorio en prestación fuera de agenda
  src/app/directives/prestaciones-select.directive.ts
  src/app/services/conceptos-turneables.service.ts
Labels: test ok

#2539 IN - Fusión de capas
  src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.html
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
  src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.html
  src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/interfaces/IOrganizacion.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/rup/components/huds/listado-internacion-huds.component.ts
Labels: test ok, has conflicts

#2649 MISC - Label de resultados
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
Labels: test ok

#2640 IN - Permisos de edicion de cama
  src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
Labels: test ok

#2673 CITAS - Agregar espacio físico en listado
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/pipes/espacioFisico.pipe.ts
Labels: test fail

#2665 IN: motivo suspensión indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
Labels: test ok

#2676 INT: mejoras visuales plan ind
  src/app/apps/rup/mapa-camas/pipes/plan-indicaciones/detalle-indicacion.pipe.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
Labels: test fail, has conflicts

#2677 INT: plan indicaciones mejoras ejecución
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-color.pipes.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-nombre.pipe.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: has conflicts

#2662 feat(MPI): No mostrar inactivos en las relaciones
  src/app/modules/mpi/components/paciente-relaciones.component.ts
Labels: test ok

#2683 In (Fix) - Visualizacion de movimientos
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
Labels: test fail

#2686 IN - Error al eliminar o modificar fecha de ingreso de una sala
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: test fail

#2688 Epidemiología - Eliminar confirmacion por nexo de la ficha covid 19
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
Labels: test ok

#2681 CITAS - Agrega nombre del día en listado de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: test ok
