Repository andes/app, pull requests merged in 2022-11, with the labels that each got.

#2748 CITAS - Loader en gestor de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
Labels: test ok

#2691 RUP - Refactor pantalla de paciente autocitado
  src/app/components/turnos/autocitar/autocitar.component.ts
  src/app/components/turnos/autocitar/autocitar.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
Labels: test ok, publicar

#2762 IN - Validar internacion capa Estadistica
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: test ok

#2731 UIUX - Tooltips recortados
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
Labels: test fail

#2705 PERINATAL - Molécula "embarazo" agregar numero
  src/app/modules/rup/components/elementos/rupers/select-base.component.ts
Labels: test fail

#2753 IN - Mostrar profesional que registro el evento en el plan de indicaciones
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
Labels: test ok

#2749 Plan indicaciones - Modificar grilla horaria del plan
  src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: test ok, has conflicts

#2767 IN - Plan de indicaciones - Bloqueo por el farmaceutico
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: test ok

#2736 IN - Quitar unidad organizativa actual al prestar cama ocupada
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
Labels: test ok

#2782 CIT - Botón para visualizar siguiente agenda
  src/app/components/reportesDiarios/resumenDiarioMensual.scss
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/dar-turnos/dar-turnos.scss
  src/app/components/turnos/dashboard/estadisticas-agendas.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: test ok

#2709 IN - formulario egreso estadistico
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test ok

#2747 CIT - mostrar prestaciones del bloque en el gestor de agendas
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: test ok
