Repository andes/app, pull requests merged in 2022-10, with the labels that each got.

#2759 IN - Error al editar camas
  src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.html
  src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
  src/app/apps/rup/mapa-camas/views/lista-espera/lista-espera.component.ts
Labels: test fail, Test local ok, publicar

#2737 CIT label contrarreferida
  src/app/components/top/solicitudes/detalleSolicitud.html
Labels: test fail

#2751 INT - Cambio filtro sector
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
Labels: test ok

#2769 CIT - sobreturnos sin pacientes
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
Labels: test fail

#2610 RUP - Control de permisos de prestacion por conceptId
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/services/conceptos-turneables.service.ts
Labels: test fail, publicar
