Repository andes/app, pull requests merged in 2022-07, with the labels that each got.

#2634 MISC - Agregar filtro por conceptos en el reporte c2
  src/app/components/reportes/encabezadoReportes.component.ts
  src/app/components/reportes/encabezadoReportes.html
Labels: test ok

#2672 IN - Labels de resultados en pantalla de censos
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
  src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Labels: test ok

#2695 Plan de indicaciones - scroll en grilla horaria
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
Labels: test ok

#2658 IN - Permitir anular prestaciones de internación
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
Labels: test ok

#2674 fix(CITAS): sacar btn disponible cuando ya lo esta
  src/app/components/turnos/gestor-agendas/pipes/botonesAgendaGeneral.pipe.ts
Labels: test fail

#2690 CITAS - Limpiar historial de selección de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: test fail

#2635 INT: pasar a internacion no censable
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: test ok

#2693 TOP - Se visualiza botón continuar registro
  src/app/components/top/pipes/botones.pipe.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: test ok

#2711 CITAS - Visualizacion de turnos agenda dinamica
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Urgente

#2703 IN (Fix): Error al inactivar cama
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
Labels: BugFix, test ok, Test local ok

#2701 IN (Fix) - Error en fechas de egreso
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/modules/mpi/components/paciente-detalle.html
Labels: BugFix, test ok, Test local ok

#2696 VAC - Quitar control de dosis
  src/app/modules/rup/components/elementos/vacunas.component.ts
  src/app/modules/rup/components/elementos/vacunas.html
Labels: test ok

#2712 IN - Plan indicaciones: Validación de formularios
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
Labels: test ok

#2710 IN - boton volver en plan de indicaciones
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: test ok

#2680 CITAS - Refactor creación de agenda
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: test ok
