Repository andes/app, pull requests merged in 2022-04, with the labels that each got.

#2614 CITAS - Aria Label en card de horarios
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: test ok

#2606 IN (Plan indicaciones) - Permitir cambiar de secciones
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/services/plantillas.service.ts
Labels: test ok

#2615 GDU-45 - Revisar error en consola al actualizar usuario
  src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
Labels: test ok

#2593 EP - Permitir descarga de un csv con reporte de seguimientos
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
  src/app/services/documentos.service.ts
Labels: test fail

#2618 RUP - (FUM) Completa campos de conceptos repetidos
  src/app/modules/rup/components/elementos/peso.component.ts
  src/app/modules/rup/components/elementos/valorFecha.component.ts
  src/app/modules/rup/services/conceptObserver.service.ts
Labels: test ok

#2613 HUDS - Posibilitar acceso a HUDS desde paciente-detalle
  angular.json
  browserslist
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/components/paciente-detalle.component.ts
  src/app/apps/auth/components/accept-disclaimer/modal-disclaimer.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/mpi/mpi-lib.module.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/rup-lib.module.ts
Labels: test ok

#2623 RUP: fix buscador clasificacion rup card
  src/app/modules/rup/components/ejecucion/buscador.html
Labels: test ok

#2630 TOP: badge huds bandeja salida
  src/app/components/top/solicitudes/solicitudes.html
Labels: test ok

#2609 feat:(CITAS): agregar icono si es un turno virtual
  src/app/components/top/pipes/isEmpty.pipe.ts
  src/app/components/top/pipes/isNotEmpty.pipe.ts
  src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
Labels: changes requested, test ok

#2622 MPI - Relaciones de un paciente
  src/app/core/mpi/components/paciente.component.ts
Labels: test ok

#2628 RUP - Error en formulas
  src/app/modules/rup/components/elementos/FormulaBase.component.ts
  src/app/modules/rup/components/elementos/FormulaBase.html
Labels: test ok

#2633 fix(citas): se agregan controles en agendas con profesionales null
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.html
Labels: test ok

#2617 RUP - Precarga de FUM en consulta de embarazo
  src/app/modules/rup/components/elementos/FormulaBase.component.ts
Labels: test ok, has conflicts
