Repository andes/app, pull requests merged in 2023-03, with the labels that each got.

#2806 TOP - Reemplaza colores de badges en solicitudes
  src/app/components/top/pipes/estado-prestacion.pipe.ts
  src/app/components/top/solicitudes/detalleSolicitud.component.ts
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
Labels: Aprobado, test ok

#2818 HUDS - Visualizar historial de turnos de paciente
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/huds/vistaHistorialTurnos.component.ts
  src/app/modules/rup/components/huds/vistaHistorialTurnos.html
  src/app/modules/rup/huds-lib.module.ts
Labels: Aprobado, test ok

#2811 CITAS - Error al suspender turnos de una agenda
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
Labels: Aprobado, test ok, Test local ok

#2716 IN: permisos para plan de indicaciones
  src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: Aprobado, test ok, publicar

#2708 feat(INT): registra eventos solo validadas
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: Aprobado, test ok, publicar

#2779 Plan de indicaciones - Control de hs (frecuencia) para ejecución de una indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
Labels: Aprobado, test ok, has conflicts, publicar

#2824 fix(RUP): Componente numerico se cambia valor por defecto a null
  src/app/modules/rup/components/elementos/valorNumerico.component.ts
Labels: test ok

#2825 TOP: corrige filtro estado bandeja salida
  src/app/components/top/solicitudes/solicitudes.html
Labels: test ok

#2829 IN - Fix condición de error para cama ocupada
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: test ok

#2820 CITAS - Se duplica agenda al clonarla
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Labels: Aprobado, test ok, Test local ok
