Repository andes/app, pull requests merged in 2023-07, with the labels that each got.

#2877 MISC-278 - Repara filtros de vistas para las novedades
  src/app/components/novedades/catalogo-novedades/filtro-novedades/filtro-novedades.component.html
  src/app/components/novedades/catalogo-novedades/filtro-novedades/filtro-novedades.scss
  src/app/components/novedades/detalle-novedad/detalle-novedad.scss
  src/app/components/novedades/lista-novedades/calendario/calendario-novedades.component.ts
  src/app/components/novedades/lista-novedades/lista-novedades.component.html
  src/app/components/novedades/novedades.component.ts
Labels: Aprobado, test ok

#2886 TYP - Modificar mensaje de comprobante
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
Labels: test ok

#2772 TM - Configuracion de internacion por conceptos turneables
  src/app/components/organizacion/configuracion-internacion.component.ts
  src/app/components/organizacion/configuracion-internacion.html
  src/app/components/organizacion/organizacion.component.ts
Labels: Aprobado, changes done, test ok

#2888 RUP - Preguntar si es Primera Vez cuando es un Evento
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: Aprobado, test ok

#2864 CIT - Implementación mockup sobreturnos
  src/app/components/turnos/citas.module.ts
  src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
  src/app/components/turnos/dar-turnos/dar-sobreturno.html
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/info-agenda.component.ts
  src/app/components/turnos/gestor-agendas/info-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, test ok

#2892 IN - Corrige request historial
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
Labels: test ok

#2764 IN - Foco al ingresar un nuevo concepto en una valoracion inicial
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
Labels: prioritario, Aprobado, test ok

#2889 IN - Deshacer internación
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
Labels: Aprobado, test ok

#2887 MPI - Auditoria de pacientes- creado por
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/interfaces/ICreatedBy.ts
  src/app/modules/auditoria/component/auditoria-listado.html
Labels: Aprobado, test ok

#2881 IN - quitar indicaciones de registro
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: Aprobado, test ok

#2897 fix(INT): Corrige error al visualizar registros en capa estadistica
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: test fail

#2898 INT - Fix egreso y filtro por documento en listados
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
Labels: test fail

#2899 IN - Fix formato de fechas
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: test ok

#2900 INT - Fix sincronizacion fecha egreso
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: test ok
