Repository andes/app, pull requests merged in 2023-05, with the labels that each got.

#2850 IN - Fijar botones al cargar una indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
Labels: Aprobado, test ok, publicar

#2835 IN - Solapamiento de funcionalidades en el sidebar
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: Aprobado, test ok, publicar

#2860 CITAS: agrega control en sobreturno
  src/app/components/turnos/dar-turnos/dar-sobreturno.html
Labels: test ok

#2819 IN - balance hidrico en el plan de indicaciones
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
  src/app/modules/rup/elementos-rup.module.ts
Labels: changes done, test ok, publicar

#2827 IN - Cambiar filtro de principios activos
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
Labels: test ok, publicar

#2841 TM (Profesionales): corrección de georeferencia con formato invalido
  src/app/components/organizacion/organizacion-create-update.component.ts
Labels: test ok

#2845 In - Plan indicaciones - No se debería poder registrar indicaciones en el pasado
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
Labels: changes done, test ok, publicar

#2843 fix(CITAS): Agrega control para permitir editar agendas pendientes de asistencia
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
Labels: Aprobado, test ok

#2833 RUP - Agrear permiso para abm de plantillas
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
Labels: Aprobado, test ok

#2836 IN - Fix movimientos con ingreso de internación a las 00 hs
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
Labels: Aprobado, test ok

#2863 RUP - No se visualizan todos los datos del turno
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: test ok

#2668 feat(HUDS): Agregar filtro de descargas pendientes
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.html
  src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.ts
  src/app/modules/visualizacion-informacion/services/export-huds.service.ts
Labels: Aprobado, test ok

#2840 TOP - Marcar solicitud seleccionada
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: Aprobado, test ok

#2861 IN - Error al editar egreso
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Labels: Aprobado, test ok, muy prioritario

#2859 feat(HUDS): modifica muestra en info de prestación
  src/app/modules/rup/components/huds/vistaPrestacion.html
  src/app/modules/rup/components/huds/vistaPrestacion.ts
Labels: Aprobado, test ok, muy prioritario

#2682 FORM - Refactor Form Builder
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/epidemiologia.module.ts
  src/app/modules/forms-builder/components/form-config/form-config.component.html
  src/app/modules/forms-builder/components/form-config/form-config.component.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
  src/app/modules/forms-builder/components/forms-list/forms-list.component.html
  src/app/modules/forms-builder/components/select-static/select-static.component.html
  src/app/modules/forms-builder/components/select-static/select-static.component.ts
  src/app/modules/forms-builder/forms.module.ts
  src/app/modules/forms-builder/services/form.service.ts
  src/app/modules/forms-builder/services/preset.resources.service.ts
Labels: Aprobado, test ok, publicar

#2816 CIT - En accion de turnos agregar datos del usuario y ordenar busquedas en el sidebar
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: Aprobado, test ok, muy prioritario

#2865 IN - Error en consola al agregar una nueva indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
Labels: prioritario, Aprobado, test ok

#2858 fix(CITAS): quita el llamado a codificación desde la app
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: prioritario, Aprobado, test ok

#2754 CIT - Agendas auditadas
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
  src/app/interfaces/ITipoPrestacion.ts
Labels: prioritario, Aprobado, test ok

#2821 TOP - Seguimiento de llamados telefonicos a pacientes
  src/app/components/top/solicitudes/historialSolicitud.html
  src/app/components/top/solicitudes/notificar-paciente.component.ts
  src/app/components/top/solicitudes/notificar-paciente.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
Labels: Aprobado, test ok, muy prioritario

#2868 HUDS - Scroll infinito en accesos a la HUDS
  src/app/modules/rup/components/huds/vista-accesos-huds.component.ts
  src/app/modules/rup/components/huds/vista-accesos-huds.html
  src/app/modules/rup/components/huds/vista-accesos-huds.scss
Labels: changes done, test ok

#2837 IN - Mostrar botón para anular internación desde historial
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
Labels: prioritario, Aprobado, test ok

#2872 fix(CIT): Cambia control de turno auditable por tipo de prestación auditable
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
Labels: test ok
