Repository andes/app, pull requests merged in 2023-11, with the labels that each got.

#2948 FEAT(RUP): Quita profesional destino al cargar solicitud
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
  src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
Labels: test fail

#2890 PRIV - Restricción por efector
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/huds/vista-accesos-huds.component.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: changes done, test ok, publicar, revisar

#2925 TOP - Deshacer una solicitud auditada
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: Aprobado, test ok

#2907 TOP - Solicitudes: nuevo estado vencido
  src/app/components/top/pipes/estado-prestacion.pipe.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.ts
Labels: Aprobado, test ok

#2938 TM - Profesionales deshabilitados
  projects/auth/src/lib/auth.service.ts
  src/app/app.component.ts
  src/app/interfaces/IProfesional.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/services/profesional.service.ts
Labels: changes done, test ok

#2951 MISC - Permite debuguear por consola
  angular.json
Labels: test fail

#2926 INT - Refactor en controles de ingreso y egreso
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: test ok, publicar
