Repository andes/app, pull requests merged in 2023-02, with the labels that each got.

#2784 TOP - Filtros fecha de actualización
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/solicitudes/solicitudes.scss
Labels: changes done, test ok

#2814 CITAS - Bugs en sidebar de gestor de agenda
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, test ok

#2799 Huds - Filtrar trastornos activos en paciente
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado, test ok

#2793 CITAS - Refactor al crear una nota en el gestor de agendas
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
Labels: changes done, test ok

#2807 CITAS- Activar turno suspendido
  src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, test ok

#2707 TM: limpieza service profesionales
  src/app/components/profesional/profesional-create-update.component.ts
  src/app/components/reportes/reporteC2.component.ts
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
  src/app/services/profesional.service.ts
Labels: test ok, publicar

#2750 IN - Error al visualizar datos de una cama
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: Aprobado, test ok, publicar

#2771 IN - No se modifica correctamente la fecha de ingreso
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: Aprobado, test ok, publicar

#2770 IN- Se visualiza edición de internación en un informe de egreso validada
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
Labels: Aprobado, test ok, publicar

#2802 CITAS - Error en agenda dinámica
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, test ok, publicar

#2717 BI - Permisos en organizaciones
  projects/auth/src/lib/auth.service.ts
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: Aprobado, test ok, publicar

#2756 GDU - Agregar filtro en listado de perfiles
  src/app/apps/gestor-usuarios/components/perfiles-detail.html
  src/app/apps/gestor-usuarios/gestor-usuarios.module.ts
  src/app/apps/gestor-usuarios/services/perfiles.http.ts
  src/app/apps/gestor-usuarios/views/perfiles-list.component.html
  src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
Labels: Aprobado, test ok
