Repository andes/app, pull requests merged in 2023-12, with the labels that each got.

#2957 MPI: corrige error que cruza pacientes por scan
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/modules/mpi/components/paciente-buscar.component.ts
Labels: prioritario, test ok

#2927 CIT - Reasigna turnos en agenda suspendida desde TOP
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: Aprobado, test ok

#2822 MPI: Implementa registro para extranjeros con DNI argentino
  src/app/app.module.ts
  src/app/core/mpi/components/busqueda-mpi.component.ts
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/datos-basicos.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/components/paciente.html
  src/app/core/mpi/services/pacienteVinculadoCache.service.ts
Labels: Aprobado, test ok, muy prioritario

#2953 IN - Restringir por efector los registros
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: Aprobado, test ok

#2933 RUP - Visualización de botones del buscador
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/buscador.scss
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado, test ok

#2854 CIT - Implementa selector de financiadores
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
  src/app/components/turnos/citas.module.ts
  src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
  src/app/components/turnos/dar-turnos/dar-sobreturno.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/interfaces/IObraSocial.ts
Labels: prioritario, Aprobado, test ok

#2966 RUP - Modifica label en boton de filtro de buscador
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: test fail

#2943 RUP - Descarga PDF de elementos de registro
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
Labels: Aprobado, test ok

#2964 TYP - Corregir Acceso al buscador
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: Aprobado, test ok

#2906 Plan indicaciones (Ref mock) - Cambios propuestos en mockups
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
  src/app/modules/rup/components/core/rup.component.ts
Labels: prioritario, Aprobado, test ok
