Repository andes/app, pull requests merged in 2023-04, with the labels that each got.

#2744 RUP: Control requerido en formulas editables
  src/app/modules/rup/components/elementos/FormulaBase.component.ts
  src/app/modules/rup/components/elementos/FormulaBase.html
Labels: test ok

#2743 PER - cambios en seguimiento perinatal
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/components/listado-perinatal.component.ts
  src/app/modules/perinatal/components/listado-perinatal.scss
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: test ok

#2813 TOP - Agrega información en vista de prestación y solicitud
  src/app/modules/rup/components/huds/vistaPrestacion.html
Labels: Aprobado, test ok

#2809 MISC - Error en filtros en el buscador de turnos y prestaciones
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Labels: Aprobado, test ok

#2832 CIT - Mostrar Obra Social en Historial de Turnos
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
Labels: changes done, test ok

#2830 IN - Inmovilizar Titulo c/Botones en Ingreso de Pacientes capa Estadística
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.scss
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: test ok

#2852 (feat)CIT: Sacar agenda dinamica que no sea del dia
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Labels: Aprobado, test ok

#2721 RUP - Se visualiza la misma prestación que genera la consulta
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: Aprobado, test ok
