Repository andes/app, pull requests merged in 2023-06, with the labels that each got.

#2844 CITAS - No clonar agendas dinamicas
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: prioritario, Aprobado, test ok

#2781 IN - controles para pacientes duplicados en camas distintas
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
Labels: Aprobado, test ok, muy prioritario

#2839 CITAS - Separar permiso de creación de solicitudes
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
Labels: prioritario, Aprobado, test ok

#2849 IN - Control en registro de una internacion
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: Aprobado, test ok

#2862 (refactor)CIT - Aplicar mockup en clonar agendas
  src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
Labels: prioritario, Aprobado, test ok

#2871 GDU - Incorpora visibilidad para local-restricted
  src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
Labels: Aprobado, test ok

#2875 IN - error al editar manualmente una fecha
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: test ok

#2876 mostrar boton revision agenda
  src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
Labels: test ok

#2808 Botón iniciar prestación
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
Labels: Aprobado, test ok, muy prioritario

#2848 (feat) CIT - Agregar configuracion de multiprofesional en agendas
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/interfaces/turnos/IAgenda.ts
Labels: Aprobado, test ok

#2866 IN - dar opción para validar o no una indicación
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
Labels: prioritario, Aprobado, test ok

#2880 IN - Limpiar filtros
  projects/auth/src/lib/auth.service.ts
Labels: Aprobado, test ok

#2884 Feat - (TYP) Visualizar mensaje de comprobantes que no se migran
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/services/facturacionAutomatica.service.ts
Labels: Aprobado, test ok
