Repository andes/app, pull requests merged in 2023-10, with the labels that each got.

#2924 IN - Cambiar nombre al seleccionar perfil
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
Labels: Aprobado, test ok

#2922 TM - Filtrar profesional por habilitado y estado
  src/app/components/profesional/profesional.component.ts
  src/app/components/profesional/profesional.html
  src/app/services/profesional.service.ts
Labels: Aprobado, test ok

#2921 TM - Deshabilitar profesional no matriculado
  src/app/components/profesional/profesional-create-update.html
  src/app/components/profesional/profesional.html
Labels: Aprobado, test ok

#2917 RUP - No evolucionar trastorno resuelto
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado, test ok

#2910 IN - Permitir botón exploracion visual
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
Labels: prioritario, Aprobado, test ok, publicar

#2893 MPI: Identidad autopercibida
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/modules/perinatal/components/listado-perinatal.component.html
Labels: prioritario, Aprobado, test ok

#2732 CIT - Control de permisos de prestaciones en profesionales
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: Aprobado, test ok, publicar

#2914 EPIDEMIOLOGIA - Actualizar ficha covid
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
Labels: changes done, test ok

#2928 IN - Listado internacion - request inválido
  src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
Labels: test ok

#2912 TABLAS MAESTRAS - Nuevo filtro tm/profesional
  src/app/components/profesional/profesional.component.ts
  src/app/components/profesional/profesional.html
  src/app/services/profesional.service.ts
Labels: changes done, test ok

#2919 HUDS - Agrega filtro de CDAs al exportar HUDS
  src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.html
  src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
Labels: test ok

#2937 fix(INT): Agrega unidades a la carga de medicamentos al plan
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
Labels: test fail

#2895 Migrar iconos a andes-font
  src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
  src/app/components/prestamosHC/prestamos-hc.component.html
  src/app/components/turnos/configuracion/espacio-fisico/espacio-fisico.html
  src/app/components/turnos/dar-turnos/calendario.html
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
  src/app/core/mpi/components/datos-basicos.html
  src/app/core/mpi/components/relaciones-pacientes.html
  src/app/modules/auditoria/component/auditoria.html
  src/app/modules/auditoria/component/reporte-errores.html
  src/app/modules/auditoria/component/vincular-pacientes.html
  src/app/modules/mpi/components/paciente-busqueda.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
  src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
  src/app/modules/rup/components/internacion/puntoInicio-internacion.html
Labels: test ok
