Repository andes/app, pull requests merged in 2023-08, with the labels that each got.

#2855 BI - Permisos por zona
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
  src/app/services/organizacion.service.ts
Labels: prioritario, changes done, test ok

#2905 fix(QUERIES): cambia filtro en descargas csv
  src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: test ok

#2853 IN- Control anular internación
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
Labels: Aprobado, test ok, publicar

#2834 MPI: Cambiar icono 'plus' por 'check' en Notas Paciente
  src/app/core/mpi/components/notas-paciente.component.ts
  src/app/core/mpi/components/notas-paciente.html
Labels: Aprobado, test ok, publicar
