Repository andes/app, pull requests merged in 2024-09, with the labels that each got.

#3067 CIT - Agendas: Enviar SMS (Notificación) activado
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: Aprobado

#3066 CIT - Demanda Insatisfecha
  src/app/components/turnos/dashboard/demandaInsatisfecha.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
Labels: changes done, publicar

#3057 PERINATAL (Fix) - Filtros de listado perinatal (De mariela)
  src/app/modules/perinatal/components/listado-perinatal.component.html
  src/app/modules/perinatal/services/carnet-perinatal.service.ts
Labels: Aprobado, publicar

#3062 CIT - Implementa filtros de reasignación de turnos
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
Labels: Aprobado, publicar

#3068 HUDS - Error al visualizar registro con relaciones
  src/app/modules/rup/components/huds/detalleRegistro.html
  src/app/modules/rup/components/huds/detalleRegistro.ts
Labels: Aprobado, publicar

#3054 HUDS - Implementa mejoras en buscador y cambios en UI
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.scss
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
  src/app/modules/rup/services/huds.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
Labels: Aprobado, publicar

#3050 MPI - Actualización select género
  projects/shared/src/lib/pipes/capitalizeFirst.pipe.ts
  projects/shared/src/lib/shared.module.ts
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/datos-basicos.html
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/mpi/components/paciente-panel.html
Labels: test ok

#3077 HUDS - Repara error al hacer click en detalle de registro
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.scss
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
Labels: publicar

#3076 HUDS - Modificar íconos en Panel de Búsqueda HUDS
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado, publicar
