Repository andes/app, pull requests merged in 2024-02, with the labels that each got.

#2973 In (Fix) - Visualizacion de registros en sidebar
  angular.json
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Labels: test ok

#2962 TYP - Listado de prestaciones no nominalizadas
  package-lock.json
  package.json
  src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.component.ts
  src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.html
  src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.scss
  src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
  src/app/directives/prestaciones-select.directive.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/huds/vistaPrestacion.ts
Labels: Aprobado, test ok

#2960 IN - Incorporar botón de búsqueda en historial
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.scss
Labels: prioritario, Aprobado, test ok

#2904 TOP: Continuidad a solicitud contrarreferida
  src/app/components/top/pipes/botones.pipe.ts
  src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/referirSolicitud.component.ts
  src/app/components/top/solicitudes/referirSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/top.routing.ts
  src/app/core/mpi/components/notas-paciente.html
Labels: prioritario, Aprobado, test ok

#2920 TYP - Mejorar llamados a la api
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
  src/app/modules/auditoria/component/auditoria.html
Labels: Aprobado, test ok

#2903 TOP - Revisar y analizar comportamiento del botón continuar
  src/app/components/top/pipes/botones.pipe.ts
  src/app/components/top/pipes/estado-prestacion.pipe.ts
  src/app/components/top/pipes/estado-solicitud.pipe.ts
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: prioritario, Aprobado, test ok

#2979 fix(EPI): Corrige error con PCR
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.html
  src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
  src/app/modules/epidemiologia/constantes.ts
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
  src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
  src/app/modules/forms-builder/services/form.service.ts
Labels: test ok

#2971 RUP - Error en carga de componente
  src/app/modules/rup/components/core/rup.component.ts
Labels: Aprobado, test ok

#2965 EP - Corregir scroll al buscar pacientes y error al guardar ficha paciente relacionado
  src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
  src/app/modules/mpi/components/paciente-relaciones.component.ts
Labels: Aprobado, test ok

#2918 RUP - Cambiar foco al iniciar prestación
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/vistaHuds.html
Labels: Aprobado, test ok

#2908 IN - Internación sin movimiento de ingreso
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
Labels: prioritario, Aprobado, test ok
