Repository andes/app, pull requests merged in 2024-08, with the labels that each got.

#3006 CIT - Implementa mockups de demanda insatisfecha
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
  src/app/components/turnos/citas.module.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/interfaces/turnos/IListaEspera.ts
Labels: changes requested, test ok

#3034 IN - Censo diario error datos de cama y paciente de internción duplicada
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
Labels: test ok

#3042 RUP - Foco en registros de consulta
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
Labels: Aprobado, test ok

#3051 HUDS- Modifica vista en evolucion de trastornos
  src/app/modules/rup/components/huds/detalleRegistro.html
Labels: Aprobado, test ok

#3053 CIT - Implementa filtro para efector en demanda insatisfecha
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
Labels: Aprobado, test ok

#3052 CIT - cerrar demanda insatisfecha
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/interfaces/turnos/IListaEspera.ts
Labels: Aprobado

#3055 CITAS (Fix) - Edición de profesionales de una agenda
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
  src/app/directives/profesionales-select.directive.ts
Labels: changes requested
