Repository andes/app, pull requests merged in 2024-10, with the labels that each got.

#3079 CIT - Gestor de agendas - Número de carpeta
  src/app/components/carpeta-paciente/carpeta-paciente.component.ts
  src/app/components/carpeta-paciente/carpeta-paciente.html
  src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
Labels: Aprobado, test ok

#3064 RUP - Implementa modal con información de envío de solicitudes
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionValidacion.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.scss
Labels: Aprobado

#3072 CIT - Modifica recuperacion de pacientes en lista de espera
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
  src/app/components/turnos/dashboard/demandaInsatisfecha.ts
  src/app/interfaces/turnos/IListaEspera.ts
  src/app/services/turnos/listaEspera.service.ts
Labels: Aprobado, publicar

#3038 LAB - Implementa vista de laboratorios
  projects/portal/src/app/services/laboratorio.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/huds-lib.module.ts
  src/app/modules/rup/services/huds.service.ts
Labels: Aprobado, publicar

#3004 IN (Fix) - Duplicación de egresos y otros
  src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.html
  src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
Labels: changes done, test ok

#3081 CIT - Bloquear botón de dar turno
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
Labels: Aprobado

#3082 CIT - Corregir la creación de agendas no nominalizadas
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: Aprobado, test ok

#3061 TM - Nuevo módulo de farmacias
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/farmacia/farmacia-create-update.component.html
  src/app/components/farmacia/farmacia-create-update.component.ts
  src/app/components/farmacia/farmacia.component.html
  src/app/components/farmacia/farmacia.component.ts
  src/app/components/farmacia/farmacia.scss
  src/app/interfaces/IFarmacia.ts
  src/app/services/farmacia.service.ts
Labels: Aprobado
