Repository andes/app, pull requests merged in 2024-05, with the labels that each got.

#2976 AM - Configuracion distancia de turnos
  src/app/components/organizacion/organizacion-create-update.component.ts
  src/app/components/organizacion/organizacion-create-update.html
Labels: Aprobado, test ok

#2996 TM - Nueva funcionalidad de plex-select
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
  src/app/directives/profesionales-select.directive.ts
  src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
  src/app/modules/perinatal/components/listado-perinatal.component.html
Labels: Aprobado, test ok

#2986 RUP - Omite previsualizacion en PDF sin validación de prestacion
  src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
Labels: Aprobado

#2983 RUP - Visualizar edad en turnos asignados en una agenda.
  projects/shared/src/lib/pipes/edad.pipe.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado

#2874 CIT - Filtro para derivaciones
  src/app/components/snomed/snomed-buscar.service.ts
  src/app/components/top/reglas/visualizacionReglas.component.ts
  src/app/components/top/reglas/visualizacionReglas.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/services/top/reglas.service.ts
Labels: prioritario, Aprobado, test ok

#2915 RUP - Filtro por actualizacion de solicitudes
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
Labels: prioritario, Aprobado, test ok

#2940 IN - Plan de indicaciones: motivo de rechazo
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
Labels: prioritario, Aprobado, test ok, publicar

#3008 HUDS - Exportacion de HUDS
  src/app/modules/rup/components/huds/vistaCDA.component.ts
  src/app/modules/rup/components/huds/vistaCDA.html
  src/app/modules/rup/services/CDA.service.ts
Labels: test ok, publicar

#2988 chore(node): amplia memoria al correr la app
  package.json
Labels: publicar

#2974 GDU - Modificar email en usuario temporal
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
  src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
  src/app/apps/gestor-usuarios/interfaces/IUsuario.ts
  src/app/apps/gestor-usuarios/views/usuarios-list.view.html
Labels: Aprobado, test ok, publicar

#2994 RUP - Unificar rutas Elementos RUP
  src/app/modules/rup/services/elementosRUP.service.ts
Labels: Aprobado, test ok, publicar

#2982 TOP - Implementa mockups para reglas de entrada
  src/app/components/top/reglas/reglas.component.css
  src/app/components/top/reglas/reglas.component.html
  src/app/components/top/reglas/reglas.component.ts
  src/app/components/top/reglas/reglas.scss
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/solicitudes/solicitudes.scss
  src/app/components/top/top.module.ts
  src/app/components/top/top.routing.ts
Labels: Aprobado, test ok, publicar

#2916 CIT - Implementar mockups de reasignación de turnos
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.scss
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
  src/app/interfaces/turnos/IAgenda.ts
  src/app/interfaces/turnos/ITurno.ts
Labels: Aprobado, test ok, publicar
