Repository andes/app, pull requests merged in 2024-01, with the labels that each got.

#2967 fix(CIT): corrige bug de obra social al generar el comprobante
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
Labels: test fail

#2955 TOP - "Visualizacion iniciar prestación" (Cambios visuales)
  package-lock.json
  package.json
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
  src/app/components/top/pipes/botones.pipe.ts
  src/app/components/top/solicitudes/anularSolicitud.component.ts
  src/app/components/top/solicitudes/anularSolicitud.html
  src/app/components/top/solicitudes/auditarSolicitud.component.ts
  src/app/components/top/solicitudes/auditarSolicitud.html
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/historialSolicitud.component.ts
  src/app/components/top/solicitudes/historialSolicitud.html
  src/app/components/top/solicitudes/notificar-paciente.component.ts
  src/app/components/top/solicitudes/notificar-paciente.html
  src/app/components/top/solicitudes/nuevaSolicitud.component.ts
  src/app/components/top/solicitudes/nuevaSolicitud.html
  src/app/components/top/solicitudes/prestacionSolicitud.component.ts
  src/app/components/top/solicitudes/prestacionSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/components/top/solicitudes/solicitudes.scss
  src/app/components/top/top.routing.ts
Labels: prioritario, Aprobado, test ok

#2949 CIT - Error al crear prestación no nominalizada
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
Labels: Aprobado, test ok

#2913 IN - Sumar laboratorios en vista de registros
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.scss
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.ts
Labels: prioritario, Aprobado, test ok

#2930 MAT - Pantalla creacion usuario
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
  src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
Labels: Aprobado, test ok

#2970 FIX(IN): Agrega componente de visualizacion
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
Labels: test ok

#2931 BI - No carga select Organizacion
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: Aprobado

#2944 IN - Fecha y hora del mapa de camas
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
  src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
Labels: Aprobado, test ok

#2952 IN- Mejoras en egreso internacion
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
  src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: Aprobado, changes done, test ok

#2942 CIT - Crear agenda con profesional habilitado
  src/app/components/profesional/profesional.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/directives/profesionales-select.directive.ts
  src/app/services/profesional.service.ts
Labels: Aprobado, test ok

#2972 PERINATAL: fix en filtros del listado
  src/app/modules/perinatal/components/listado-perinatal.component.ts
Labels: test ok

#2934 RUP - Actualizar información del paciente desde RUP
  src/app/core/mpi/components/paciente.component.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/mpi/components/paciente-detalle.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-estatico.component.ts
  src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-estatico.html
Labels: Aprobado, test ok

#2911 IN - Mejorar consulta para listado médico
  projects/shared/src/lib/server/resource-base.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
  src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
Labels: Aprobado, test ok
