Repository andes/app, pull requests merged in 2024-03, with the labels that each got.

#2977 TYP (Fix) - Separa cache de busqueda en cada submodulo
  src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.component.ts
  src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
  src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
Labels: Aprobado

#2950 MPI - Modifica condición para botón de "ignorar y guardar"
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/components/paciente.html
Labels: Aprobado, test ok

#2941 CIT - Ventanilla: poder dar turno con llave
  src/app/components/turnos/dar-turnos/calendario-dia.class.ts
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
  src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
Labels: Aprobado, test ok

#2936 IN - Cargar campo para diferenciar prestación del Plan de Indicaciones
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/mpi/components/paciente-listado.component.ts
  src/app/modules/mpi/components/paciente-listado.html
  src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Labels: prioritario, Aprobado, test ok

#2961 IN - nuevo rol de internacion: farmacia
  src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
  src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-color.pipes.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-nombre.pipe.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
  src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
Labels: Aprobado, test ok

#2954 IN - Eliminar indicación en estado borrador
  src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
  src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
  src/app/modules/rup/components/core/rup.component.ts
Labels: prioritario, Aprobado, test ok
