Repository andes/app, pull requests merged in 2024-06, with the labels that each got.

#2999 MPI - Pacientes sin domicilio real
  src/app/core/mpi/components/datos-contacto.component.ts
  src/app/core/mpi/components/datos-contacto.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/interfaces/IDireccion.ts
Labels: changes done, test ok, publicar

#3016 fix(HUDS): Corrige ruta al descargar pdf
  src/app/modules/rup/services/CDA.service.ts
Labels: Aprobado, publicar

#2985 CIT - FIX: modificar esquema de obra social al dar sobreturno
  src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
Labels: Aprobado, publicar

#3000 UIUX - Implementar extensión de archivos
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.scss
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/core/mpi/components/documentos-paciente.component.ts
  src/app/core/mpi/components/documentos-paciente.html
  src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
  src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
  src/app/modules/rup/components/elementos/adjuntarDocumento.html
Labels: Aprobado, test ok, publicar

#3010 PRIV - Agregar campo observación en motivos
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
  src/app/modules/rup/components/huds/vista-accesos-huds.html
Labels: Aprobado, test ok, publicar

#3009 HUDS - Declaración jurada de acceso a la HUDS
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
Labels: Aprobado, test ok, publicar

#2946 CIT - Ventanilla: No dar turno en agenda dinamica
  src/app/components/turnos/dar-turnos/calendario.component.ts
  src/app/components/turnos/dar-turnos/calendario.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: Aprobado, test fail, publicar

#3015 CIT - Publicar agendas en el pasado
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Labels: Aprobado, test ok

#2991 CIT - Error en auditoria de agendas en turnos disponibles
  src/app/components/turnos/gestor-agendas/operaciones-turnos/agregar-nota-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/agregar-nota-turno.html
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/modules/rup/components/huds/vistaHistorialTurnos.html
Labels: Aprobado, publicar

#2995 BI - Detalle en variables query
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.scss
  src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Labels: Aprobado, test ok, publicar

#3002 (FEAT) Demanda Insatisfecha: pasar funcionalidad a API
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dashboard/demandaInsatisfecha.html
  src/app/components/turnos/dashboard/demandaInsatisfecha.ts
  src/app/services/turnos/listaEspera.service.ts
Labels: changes done, publicar

#3011 CIT - Edición de profesional en agenda
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Labels: Aprobado, publicar

#2945 RUP - Implementa mockups en punto de inicio
  src/app/components/turnos/autocitar/autocitar.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
  src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
  src/app/modules/rup/components/ejecucion/prestacionCrear.html
  src/app/modules/rup/components/ejecucion/prestacionCrear.scss
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
  src/app/modules/rup/components/ejecucion/puntoInicio.scss
  src/app/modules/rup/components/variables.scss
Labels: changes done, test ok

#3003 IN - Implementa periodos censables en internacion
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.component.ts
  src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.html
  src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.scss
  src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Labels: Aprobado, test ok, publicar

#3030 TOP - Fix en ContinuarRegistro de TOP
  src/app/components/top/solicitudes/solicitudes.component.ts
Labels: test ok
