Repository andes/app, pull requests merged in 2025-03, with the labels that each got.

#3152 RUP - Agregar diagnósticos a la receta
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
Labels: Aprobado, receta

#3107 IN - Modificar carga de OS en alta de internación capa estadística
  src/app/apps/rup/mapa-camas/constantes-internacion.ts
  src/app/apps/rup/mapa-camas/mapa-camas.module.ts
  src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: Aprobado, Test local ok

#3125 MPI - Implementa seleccion editable de obras sociales
  src/app/app.module.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.html
  src/app/components/turnos/dar-turnos/seleccionar-financiador.scss
  src/app/core/mpi/components/obra-social.component.ts
  src/app/core/mpi/components/obra-social.html
  src/app/core/mpi/components/paciente.html
Labels: Aprobado

#3071 RUP - Concepto Receta Autorización
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/buscador.html
Labels: Aprobado, test ok, receta

#3088 PLEX - Actualiza a version 8.0.11
  package-lock.json
  package.json
Labels: Aprobado, has_conflicts, publicar

#3124 TOP - Corregir mensaje de solicitud en curso que no corresponde
  src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
Labels: Aprobado

#3155 RUP - Receta: control para evitar duplicar recetas
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
Labels: Aprobado, receta

#3115 IN - Cambiar periodos de registros de internación
  src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
  src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
  src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
  src/app/modules/mpi/components/paciente-detalle.component.ts
  src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
  src/app/modules/rup/services/huds.service.ts
  src/app/modules/rup/services/prestaciones.service.ts
  src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
Labels: En revisión, changes done
