Repository andes/app, pull requests merged in 2025-02, with the labels that each got.

#3140 HUDS (Fix) - Scroll infinito en listado de accesos
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/ejecucion/vistaHuds.scss
Labels: Aprobado

#3127 RUP - Modifica modal de evolución de trastorno
  src/app/modules/rup/services/ejecucion.service.ts
Labels: falta 1 revisor!

#3132 IN (Fix) - Información de ingreso incompleta
  src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
  src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Labels: falta 1 revisor!

#3142 RUP - Habilitar tab del buscador y otras cosas
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: Aprobado

#3137 CIT - Mostrar origen del turno REASIGNADO en la agenda
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado

#3134 HUDS - Registros faltantes en HUDS en internación
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
Labels: Aprobado

#3136 IN - Nuevo registro: Error en control de horas
  src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
Labels: changes done, falta 1 revisor!

#3145 HUDS - Eliminar el registro de acceso a la HUDS cuando no corresponde
  src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
  src/app/modules/rup/components/ejecucion/puntoInicio.html
Labels: Aprobado

#3143 CIT (Fix) - Error en controles de profesional y espacio fisico
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
Labels: changes done

#3130 CIT - Control por turnos repetidos en ventanilla
  src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
  src/app/components/turnos/dar-turnos/dar-sobreturno.html
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/dar-turnos.html
Labels: Aprobado

#3117 CIT - Notificaciones: limpiar código innecesario
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
  src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
  src/app/services/turnos/sms.service.ts
Labels: changes done

#3093 LAB - Paciente temporal enviar DNI parentezco
  projects/portal/src/app/services/laboratorio.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Labels: Aprobado

#3090 CIT - clonar agendas si los conceptos turneables tienen ámbito ambulatorio
  src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
  src/app/components/turnos/gestor-agendas/gestor-agendas.html
  src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Labels: Aprobado, Test local ok

#3151 RUP - error en select dinámico
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: changes done, receta

#3133 HUDS - Visualización de Recetas en la HUDS
  projects/portal/src/app/services/receta.service.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/hudsBusqueda.scss
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
  src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.html
  src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.scss
  src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.ts
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
  src/app/modules/rup/components/ejecucion/vistaHuds.html
  src/app/modules/rup/components/ejecucion/vistaHuds.scss
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
  src/app/modules/rup/components/huds/vistaReceta.html
  src/app/modules/rup/components/huds/vistaReceta.scss
  src/app/modules/rup/components/huds/vistaReceta.ts
  src/app/modules/rup/components/variables.scss
  src/app/modules/rup/huds-lib.module.ts
  src/app/modules/rup/services/huds.service.ts
Labels: changes done, receta

#3153 RUP - Edit manual cantidad de medicamento
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
  src/app/modules/rup/components/elementos/recetaMedica.scss
Labels: has_conflicts
