Repository andes/app, pull requests merged in 2025-05, with the labels that each got.

#3178 RUP: cambia la forma de acceder a las cantidades de presentaciones comerciales
  src/app/apps/mitos/services/snomed.service.ts
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
Labels: Aprobado

#3173 Receta - Visualizacion de indicaciones
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
  src/app/modules/rup/components/elementos/recetaMedica.scss
Labels: publicar, receta

#3170 RUP - Implementa datos para tratamiento prolongado
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
Labels: Aprobado, changes done

#3176 fix(CIT) - Corrección de múltiples errores
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
  src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
Labels: Aprobado, publicar

#3163 TOP - Buscar internación
  src/app/components/top/solicitudes/adjuntarDocumento.scss
  src/app/components/top/solicitudes/detalleSolicitud.component.ts
  src/app/components/top/solicitudes/detalleSolicitud.html
  src/app/components/top/solicitudes/solicitudes.component.ts
  src/app/components/top/solicitudes/solicitudes.html
  src/app/core/mpi/services/paciente.service.ts
Labels: changes done

#3156 CIT - Agrega numero de afiliado a selector de prestadores
  src/app/components/turnos/dar-turnos/dar-turnos.component.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.html
  src/app/components/turnos/dar-turnos/seleccionar-financiador.scss
Labels: Aprobado

#3165 RUP - Bloquea edicion de recetas
  src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
  src/app/modules/rup/components/core/rup.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
  src/app/modules/rup/components/elementos/recetaMedica.scss
  src/app/modules/rup/services/ejecucion.service.ts
Labels: Aprobado, receta

#3182 RUP - Evita prescripción como diagnóstico
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
Labels: receta

#3148 HUDS - Habilitacion parcial de la HUDS
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
  src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
  src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
Labels: Revisar detalles, receta

#3183 Receta: actualiza get de recetas
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
Labels: receta

#3175 INT - Ver labos de SIL2 en los registros de internación
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
  src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
  src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Labels: changes done, publicar

#3188 RUP: Corrige visualizacion del detalle de protocolo del SIL2
  src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Labels: publicar

#3168 HUDS - Se agrega estado, tipo de muestra y prácticas solicitadas
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
  src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
Labels: Aprobado, publicar

#3185 feat(MPI-448): Convivientes - completar circuito en relacion
  src/app/core/mpi/components/paciente.component.ts
Labels: publicar
