Repository andes/app, pull requests merged in 2025-06, with the labels that each got.

#3200 HUDS: habilita check al suspender medicamento
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Labels: Aprobado

#3191 HUDS - Filtro Elemento de Registro
  src/app/modules/rup/components/ejecucion/buscador.component.ts
  src/app/modules/rup/components/ejecucion/buscador.html
  src/app/modules/rup/components/ejecucion/buscador.scss
  src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
  src/app/modules/rup/components/ejecucion/hudsBusqueda.html
  src/app/modules/rup/components/ejecucion/hudsBusqueda.scss
Labels: Aprobado

#3186 CIT - Visualización de historial de turnos
  src/app/app.module.ts
  src/app/components/turnos/dashboard/estadisticas-paciente.scss
  src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
  src/app/components/turnos/dashboard/estadisticas-pacientes.html
  src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
  src/app/components/turnos/punto-inicio/turnos-paciente.html
  src/app/components/turnos/punto-inicio/turnos-paciente.scss
  src/app/services/turnos/historial-turnos.service.ts
Labels: Aprobado

#3207 MPI-442: Documentos Adjuntos: Agregar control
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
  projects/shared/src/lib/components/galeria-archivos/galeria-archivos.scss
  projects/shared/src/lib/pipes/fileSize.pipe.ts
  projects/shared/src/lib/shared.module.ts
  src/app/core/mpi/components/documentos-paciente.component.ts
  src/app/core/mpi/components/documentos-paciente.html
  src/app/shared/components/upload-file.component.ts
Labels: publicar

#3204 Recetas: Mejoras en carga de diagnósticos
  src/app/modules/rup/components/elementos/recetaMedica.component.ts
  src/app/modules/rup/components/elementos/recetaMedica.html
Labels: publicar, receta
