Repository andes/app, pull requests merged in 2025-08, with the labels that each got.

#3218 Receta: corrige error ortografia
  src/app/apps/rup/mapa-camas/constantes-internacion.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado

#3213 MPI - Permite numero de afiliado con todos los financiadores
  src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
  src/app/components/turnos/dar-turnos/seleccionar-financiador.html
Labels: Aprobado, changes done

#3215 MPI-454: Registrar paciente fallecido
  src/app/core/mpi/components/datos-basicos.component.ts
  src/app/core/mpi/components/datos-basicos.html
  src/app/core/mpi/components/datos-contacto.component.ts
  src/app/core/mpi/components/datos-contacto.html
  src/app/core/mpi/components/paciente.component.ts
  src/app/core/mpi/interfaces/IPaciente.ts
  src/app/modules/mpi/components/paciente-detalle.html
Labels: changes done

#3198 HUDS - Visualizar el listado de dispensas parciales
  src/app/modules/rup/components/huds/vistaReceta.html
  src/app/modules/rup/components/huds/vistaReceta.scss
  src/app/modules/rup/components/huds/vistaReceta.ts
Labels: Aprobado, changes done, receta

#3154 CIT - Error al volver a disponible turno suspendido
  src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
  src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
  src/app/components/turnos/gestor-agendas/turnos.component.ts
  src/app/components/turnos/gestor-agendas/turnos.html
Labels: Aprobado, Test local ok
